### ISSUE TITLE
Webpage not found error 404

### ISSUE THREAD

**Issue by Yaswhanth** [dotnet/website-feedback#10]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run
Operating System: ubuntu linux 22.04Lts

![Screenshot from 2024-02-12 22-06-17](https://github.com/dotnet/website-feedback/assets/159437739/69d77285-3dc8-41ff-ba3d-b0bf353596e6)

**Comment by mairaw** [comment]
I'm sorry to hear you're running into issues @Yaswhanth.

Have you tried opening the route as instructed in the tutorial?
In your case, it should be localhost:5090/weatherforecast.
