### ISSUE TITLE
C# extenstion installed in Visual studio code but not showing successful in terminal

### ISSUE THREAD

**Issue by ykannareddy356** [dotnet/website-feedback#102]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

I have installed C# extension in Visual studio code but while running in terminal dotnet command it is not showing successful getting error as not recognised
![dotnet error](https://github.com/dotnet/website-feedback/assets/108452082/03a71d8d-2074-4357-adaa-6b06653d9373)

### Description

I have installed C# extension in Visual studio code but while running in terminal dotnet command it is not showing successful getting error as not recognised.
![dotnet error](https://github.com/dotnet/website-feedback/assets/108452082/e0696d7d-8565-42b0-8d12-b116ac470107)

**Comment by mairaw** [comment]
Have you restarted VS Code after the .NET SDK installation? Can you try running the `dotnet` command on a command prompt window and see if you get the same results?
