### ISSUE TITLE
Error create docker image

### ISSUE THREAD

**Issue by www741147** [dotnet/website-feedback#103]
### URL

https://dotnet.microsoft.com/zh-cn/learn/aspnet/microservice-tutorial/docker-image

### Operating system

windows

### Description

when i input the command "docker build -t mymicroservice ."
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.

![image](https://github.com/dotnet/website-feedback/assets/6457259/675d484b-0b86-42cd-af3b-1bb8dffdaefd)

I don't know why display this error, how can i solve this problem?

**Comment by katiesavage** [comment]
Did you run into any other errors in the previous tutorial steps?

@baronfel any idea what's causing this?
