### ISSUE TITLE
if there is another project open, new project does not appead in explorer

### ISSUE THREAD

**Issue by yozsoy** [dotnet/website-feedback#105]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

macos

### More information about your system

if there is another project open, new project does not appead in explorer

### Description

if there is another project open, new project does not appead in explorer

**Comment by mairaw** [comment]
Sorry it took us a while to get back to you. Is this still happening? can you show us what that looks like in your VS Code with a screenshot?
