### ISSUE TITLE
I can't create a c# console app, using c# dev kit in OS version

### ISSUE THREAD

**Issue by Jameswangxz** [dotnet/website-feedback#107]
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create

### Operating system

macos

### More information about your system

Mac OS version with M3 pro 

### Description

I tried to create a new console app, using c# dev kit in visual studio code.
I followed the steps on Microsoft's page, but I get the following error:
<img width="462" alt="截屏2024-03-31 21 26 36" src="https://github.com/dotnet/website-feedback/assets/165566253/76bd436c-5ab4-4c9b-9cbe-23f638bc11fc">
I aready installed the .net sdk arm64:
<img width="437" alt="截屏2024-03-31 21 27 01" src="https://github.com/dotnet/website-feedback/assets/165566253/e06a7fad-53ad-4d6a-b42c-3c80de0dc585">
Also I already installed the c# dev kit
<img width="712" alt="截屏2024-03-31 21 33 23" src="https://github.com/dotnet/website-feedback/assets/165566253/2a1154aa-eb16-4130-a8a1-fdd5884c78c5">
Why is the error? And how to fix it?

**Comment by mairaw** [comment]
Can you share the results of `dotnet --info`?

@timheuer @webreidi any suggestions?
