### ISSUE TITLE
no puedo agregar el sdk dotnet a mi visual studio ! no se si sera mejor instalar aparte el visual que viene para c# de microsoft que creo que no me va a tirar tantos errores

### ISSUE THREAD

**Issue by Polaco88h** [dotnet/website-feedback#108]
### URL

https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

![Captura de pantalla 2024-04-02 130335](https://github.com/dotnet/website-feedback/assets/114850274/a09e510c-3a74-4409-b478-b87a79400525)

### Description

windows 10 x64 tengo el sdk instalado ya reinicie dos veces .
tengo el visual studio 1.87.2  y lo inicie desde el cmd ,pero me sigue tirando error!

### dotnet --info

Fatal error. Internal CLR error. (0x80131506)

**Comment by mairaw** [comment]
Can you run `dotnet --info` outside of VS Code? Like in a command prompt or PowerShell window or do you get the same error?
