### ISSUE TITLE
Ran an issue

### ISSUE THREAD

**Issue by AnjaliAmbadare** [dotnet/website-feedback#110]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

windows

### Description

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows  PS C:\my folder\new js folder>  & 'c:\Users\v-aambadare\.vscode\extensions\ms-dotnettools.csharp-2.23.15-win32-x64\.debugger\x86_64\vsdbg.exe' '--interpreter=vscode' '--connection=512f45baf8334495ab16c7fd56e41b00'  Hello, World! PS C:\my folder\new js folder>  & 'c:\Users\v-aambadare\.vscode\extensions\ms-dotnettools.csharp-2.23.15-win32-x64\.debugger\x86_64\vsdbg.exe' '--interpreter=vscode' '--connection=8e9ce0883957407d858fc844ff107ebb'

**Comment by mairaw** [comment]
On your description, I see the output expected:
'Hello, World!'

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows PS C:\my folder\new js folder> & 'c:\Users\v-aambadare.vscode\extensions\ms-dotnettools.csharp-2.23.15-win32-x64.debugger\x86_64\vsdbg.exe' '--interpreter=vscode' '--connection=512f45baf8334495ab16c7fd56e41b00' **Hello, World!** PS C:\my folder\new js folder> & 'c:\Users\v-aambadare.vscode\extensions\ms-dotnettools.csharp-2.23.15-win32-x64.debugger\x86_64\vsdbg.exe' '--interpreter=vscode' '--connection=8e9ce0883957407d858fc844ff107ebb'

It seems things are working. Can you confirm?
