### ISSUE TITLE
MyConsoleApp tutorial will not run

### ISSUE THREAD

**Issue by greg-matian** [dotnet/website-feedback#114]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### More information about your system

MAC OS 14.4.1 (23E224)

### Description

attempting to run the tutorial MyConsoleApp per instructions I get the following displayed in VSCode terminal view:

Users/matiang1/.vscode/extensions/ms-dotnettools.csharp-2.23.15-darwin-x64/.debugger/x86_64/vsdbg --interpreter=vscode --connection=/var/folders/nr/0r980z0544z6r916_f1nwfzcq03150/T/CoreFxPipe_vsdbg-ui-0b27e283e56d483eb343b593fd5d3adc 
You must install .NET to run this application.

App: /Users/<xxxx>/Desktop/Code/MyConsoleApp/MyConsoleApp/bin/Debug/net8.0/MyConsoleApp
Architecture: x64
App host version: 8.0.4
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx-x64&os=osx.14&apphost_version=8.0.4
USSFO-5LGJG5J:MyConsoleApp <xxxx>$ 

### dotnet --info

.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.204/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/Users/matiang1/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Can you try running the project from outside VS Code and see if it works?

Go to your project location and type `dotnet run` on a terminal window. Does it work?

@webreidi  @timheuer do you have other suggestions?

**Comment by timheuer** [comment]
@greg-matian Can you also try restarting VSCode?

**Comment by reillysiemens** [comment]
Having this same issue. Restarting doesn't fix the problem. Outside of VS Code I have no problem running `dotnet run` and getting the application to compile and run. My installation of .NET is in `$HOME/.dotnet` after a [manual installation](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install).

**Comment by reillysiemens** [comment]
I'm not certain yet, but it _looks_ like I was missing the
```shell
export DOTNET_ROOT="${HOME}/.dotnet"
```
in my shell config.

Is that environment variable critical? If so it didn't see as clear as it could have been during the tutorial or during the .NET installation. I just made sure the `dotnet` binary was on my `$PATH`.

**Comment by reillysiemens** [comment]
That information is actually made pretty clear at the [bottom of the .NET download page](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.204-linux-x64-binaries), but it was off screen and the download was successful, so I did not see that the first time around.

**Comment by mairaw** [comment]
I'm glad you got it working. I'll add a ticket on our system for when we redesign the download page to consider the hidden instructions below the fold and how we can make that more visible to customers.
