### ISSUE TITLE
HELP STEP UP 

### ISSUE THREAD

**Issue by AnuragGajula** [dotnet/website-feedback#117]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

windows 11 
x64

### Description

PS C:\Users\Prashanth Gajula\Desktop\VSCODES\DOTNET> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### dotnet --info

PS C:\Users\Prashanth Gajula\Desktop\VSCODES\DOTNET> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
If you run the command `dotnet --info` outside of VSCode, do you also get an error? if not, can you share the results?
