### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luisboss1** [dotnet/website-feedback#119]
### URL

https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

![image](https://github.com/dotnet/website-feedback/assets/121136889/9b3e118c-13eb-43d4-a021-1b66ef16077b)

### Description

cundo voy a crear n archivo solo me deja un json
[error_dotnet.docx](https://github.com/dotnet/website-feedback/files/15013369/error_dotnet.docx)

**Comment by mairaw** [comment]
Can you open a command prompt/powershell window and type `dotnet --info` so we can see what you have installed?
