### ISSUE TITLE
Build failed on .NET Tutorial - Your First Microservice - Run your service

### ISSUE THREAD

**Issue by nimishshete93** [dotnet/website-feedback#122]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run

### Operating system

windows

### More information about your system

Win 11 (x64)

### Description

C:\Users\Nimish\Mymicroservice\Mymicroservice\Mymicroservice.csproj : error NU1100: Unable to resolve 'Microsoft.AspNet
Core.OpenApi (>= 8.0.4)' for 'net8.0'.
C:\Users\Nimish\Mymicroservice\Mymicroservice\Mymicroservice.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspN
etCore (>= 6.4.0)' for 'net8.0'.

### dotnet --info

.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Can you try running `dotnet restore` and `dotnet build`?

You can also try checking the instructions listed at https://github.com/dotnet/core/issues/6193#issuecomment-827395026

Did you install chocolatey by any chance? Sometimes we see this issue.
