### ISSUE TITLE
create APP

### ISSUE THREAD

**Issue by Jhon11223344556677** [dotnet/website-feedback#123]
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

X64

### Description

During step 6 of creating the application, there was a problem naming the item MyConsoleApp in the command panel

### dotnet --info

![QQ截图20240419205622](https://github.com/dotnet/website-feedback/assets/167536972/4c38af89-8aa7-4345-a5ea-85d62ce55006)

**Comment by mairaw** [comment]
It seems that the .NET SDK installation was unsuccessful on the previous step.

How are you trying to install the .NET SDK? Have you tried changing the timeout value?
