### ISSUE TITLE
Cannot connect to localhost 

### ISSUE THREAD

**Issue by julie-mindcapers** [dotnet/website-feedback#124]
### URL

Copying the line from the tutorial creates an unreachable service when run as a non-admin user. A warning would at least have saved me many hours.

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run

### Operating system

windows

### More information about your system

Copying the line from the tutorial creates an unreachable service when run as a non-admin user. A warning would at least have saved me many hours.

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run

### Description

Copying the line from the tutorial creates an unreachable service when run as a non-admin user. A warning would at least have saved me many hours.

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run

### dotnet --info

C:\xxx>dotnet -info
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet--info does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by mairaw** [comment]
Which line are you referring to? I'll look into the permissions needed and perhaps we can add some clarifications in the pre-requisites. I believe you do need admin access to install the SDK, but shouldn't need for anything else.

Also, can you try running `dotnet --info` again? It should be working. Maybe there was something missing like a space?

**Comment by julie-mindcapers** [comment]
dotnet new webapi -o MyMicroservice --no-https

**Comment by mairaw** [comment]
What error do you get when you try to run that command with a non-admin account?
