### ISSUE TITLE
.NET location: Not found

### ISSUE THREAD

**Issue by patsy005** [dotnet/website-feedback#125]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

windows

### Description

I followed the tutorial, reinstall my .net runtime and sdk and while trying to run code I have following output : 
```

Architecture: x64
App host version: 8.0.4
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win-x64&os=win10&apphost_version=8.0.4 
```
I used link provided from console to reinstall .net runtime, open my machine again and it's still does not see .net runtime

Any tips ?

**Comment by mairaw** [comment]
Can you share what `dotnet --info` returns?
