### ISSUE TITLE
Blazor web app doesn't exist

### ISSUE THREAD

**Issue by OnThisPhone** [dotnet/website-feedback#127]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

windows

### Description

The tutorial is outdated.

**Comment by mairaw** [comment]
Blazor Web App is actually a new template in .NET 8. What is the version of Visual Studio 2022 that you're running? For this tutorial to work, you need to be on 17.8 and later versions.
