### ISSUE TITLE
c # pragram.cs

### ISSUE THREAD

**Issue by Byukusenge3** [dotnet/website-feedback#130]
### URL

3

### Operating system

windows

### More information about your system

16.0 GB (15.7 GB usable)

### Description

i dont know how to add c# pragram.cs 

### dotnet --info

Downloading package 'Razor Language Server Telemetry (Windows / x64)' (9683 KB).Failed at stage: downloadPackage
Cancelled downloading https://download.visualstudio.microsoft.com/download/pr/e6af6483-13d8-4a24-8f9d-d418fb39bd97/95481d73dc1be495fccce0372813edac/devkittelemetry-win-x64-7.0.0-preview.24168.4.zip.

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\3326901b"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 10:36:03 AM] [Program] Language server initialized
...................

**Comment by Byukusenge3** [comment]
no

**Comment by mairaw** [comment]
Are you following this tutorial?
https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/intro

Your issue seems similar to
https://github.com/dotnet/vscode-csharp/issues/4497
https://github.com/dotnet/vscode-csharp/issues/2843
