### ISSUE TITLE
cant get past 1st step

### ISSUE THREAD

**Issue by Perk2008** [dotnet/website-feedback#132]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

say this when i try to put in dotnet: dotnet : The term 'dotnet' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandN
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandN
   otFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
What happens if you open a command prompt window outside of VS Code and type dotnet? Do you still get an error? Have you tried restarting VS Code?
