### ISSUE TITLE
dotnet folder not found with #C extention

### ISSUE THREAD

**Issue by miagiulia** [dotnet/website-feedback#133]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

When I move to the terminal part ad the instructions said, this one is the massage that I found:
PS C:\Users\Utente> dotnet
dotnet : Termine 'dotnet' non riconosciuto come nome di cmdlet, funzione, programma 
eseguibile o file script. Controllare l'ortografia del nome o verificare che il percorso sia  
incluso e corretto, quindi riprovare.
In riga:1 car:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException    
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
What happens if you open a command prompt window outside of VS Code and type dotnet? Do you still get an error? Have you tried restarting VS Code?
