### ISSUE TITLE
Content wrong

### ISSUE THREAD

**Issue by jnz-jahangir** [dotnet/website-feedback#134]
### URL

https://dotnet.microsoft.com/zh-cn/learn/aspnet/blazor-tutorial/modify

### Operating system

windows

### Description

Counter IncrementAmount="10" is wrong
it should be Counter IncrementAmount=10

**Comment by mairaw** [comment]
Adding @danroth27 to confirm but I just ran the code and IntelliSense even suggests the quotes, even though I was able to run with or without quotes. Do you get an error if you run with quotes?

I did notice though a small formatting improvement I can make on this page though
![image](https://github.com/dotnet/website-feedback/assets/12971179/9f96b6a6-fd53-433b-863d-d8cda2524c06)

**Comment by danroth27** [comment]
HTML5 doesn't require the quotes if the attribute value doesn't have spaces in it, but stylistically we typically include them.

**Comment by mairaw** [comment]
Closing since code is correct. But please let us now if anything is not working for you @jnz-jahangir.

**Comment by jnz-jahangir** [comment]
@mairaw @danroth27 Actually I mean this code
![Screenshot_2024-05-03-12-28-15-971_com android chrome-edit](https://github.com/dotnet/website-feedback/assets/25359314/b243e627-3517-4660-acb1-dcc5e0e5a01e)
When I do the same as the picture, I receive an error on the last line. But it works when I remove the quote to make <Counter IncrementAmount="10" /> be <Counter IncrementAmount=10 />. If it is possible the quote make the IncrementAmount be a string varible rather than an integer varible?

**Comment by danroth27** [comment]
> When I do the same as the picture, I receive an error on the last line.

@jnz-jahangir Could you please share with us the exact error you are seeing? It would help if you could share the contents of *Counter.razor* with us.

**Comment by jnz-jahangir** [comment]
> > When I do the same as the picture, I receive an error on the last line.
> 
> @jnz-jahangir Could you please share with us the exact error you are seeing? It would also help if you could share the contents of _Counter.razor_ with us.
Sorry, unfortunately, I am not able to make that error show again. Maybe there were other weird errors happening at the time. I'm sorry to bother you and Thanks for your help.

**Comment by mairaw** [comment]
I'm glad things are working normally now. No need to apologize.
