### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by jamesjaveluna** [dotnet/website-feedback#135]
### URL

I followed thi one, but I cannot start the project. https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

I receive this error

/Build started at 12:55 AM...
1>------ Build started: Project: BlazorApp1, Configuration: Debug Any CPU ------
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>CSC : warning CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'.
1>E:\Downloads\BlazorApp1\Program.cs(1,18,1,28): error CS0234: The type or namespace name 'Components' does not exist in the namespace 'BlazorApp1' (are you missing an assembly reference?)
1>Done building project "BlazorApp1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:55 AM and took 08.907 seconds ==========

### Operating system

windows

### Description

I created a new project by following the guide shown here, https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create but I cannot start it.

**Comment by mairaw** [comment]
Can you confirm what is your Visual Studio version and also open a new command prompt and type `dotnet --info` on the location of the project to see what you have installed?

Thanks!
