### ISSUE TITLE
Error when creating docker Image

### ISSUE THREAD

**Issue by muhammadaqib123321** [dotnet/website-feedback#138]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image

### Operating system

windows

### Description

C:\Users\m.aqib\MyMicroservice>docker build -t mymicroservice .
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/_ping": open //./pipe/docker_engine: The system cannot find the file specified.

when i run this command to create docker image it give me an above error

**Comment by katiesavage** [comment]
Did you get errors in any of the previous steps? 

@baronfel, any ideas about what's going on here?

**Comment by baronfel** [comment]
In this case the user hasn't started Docker. The error they have provided is coming right from Docker. They should start Docker Desktop and try again.
