### ISSUE TITLE
dotnet : The term 'dotnet' is not recognized

### ISSUE THREAD

**Issue by Brogoming** [dotnet/website-feedback#139]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

dotnet : The term 'dotnet' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [],  
   CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
Have you tried restarting VS Code? If you type dotnet --info on a terminal outside of VS Code (command prompt or powershell), does it still say that that dotnet was not recognized?
