### ISSUE TITLE
Run Blazor Web App - The app does not launch in the browser automatically

### ISSUE THREAD

**Issue by luyendt** [dotnet/website-feedback#140]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### More information about your system

Windows 11 
Visual Studio Microsoft Visual Studio Professional 2022 (64-bit) -  Version 17.10.0 Preview 3.0
Chrome and Edge are available

### Description

I follow the Web App Blazor tutorial, at the step Run your app. the app does not open in any browser. All I have is a console window like the below screenshot:
![image](https://github.com/dotnet/website-feedback/assets/19405308/915d8f3e-b172-4a6b-87a3-f57b5c5c3379)

**Comment by luyendt** [comment]
Update:
I have to manually open a chrome tab with url: http://localhost:5000/ , then the app is shown:

![image](https://github.com/dotnet/website-feedback/assets/19405308/4ede55eb-0715-4d09-8d2a-37e2b5fc6fa6)

**Comment by mairaw** [comment]
And what is the option you have selected in your debug menu?
It should look similar to this
![image](https://github.com/dotnet/website-feedback/assets/12971179/b94a7cbc-7ce2-45ad-9d22-d0db89832b2c)

@danroth27 any other suggestions?

**Comment by luyendt** [comment]
> And what is the option you have selected in your debug menu? It should look similar to this ![image](https://private-user-images.githubusercontent.com/12971179/330650016-b94a7cbc-7ce2-45ad-9d22-d0db89832b2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDQzODgsIm5iZiI6MTcxNTc0NDA4OCwicGF0aCI6Ii8xMjk3MTE3OS8zMzA2NTAwMTYtYjk0YTdjYmMtN2NlMi00NWFkLTlkMjItZDBkYjg5ODMyYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAzMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOTkzYzQ1MjhhZjE1NWFhZWJjYTIwOWU2YjhjNzUyMDkyZGM4ZDA5ZWY2YjBmYTcyYzcxNzk5NGQwOTg4NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l3Zv-exXUDZPx083-b28viTjEg5p5bopy6j4hWS6edA)
> 
> @danroth27 any other suggestions?

It now can launch well on both Chrome and Edge. Thank you.

**Comment by mairaw** [comment]
Great to hear! ❤️
