### ISSUE TITLE
i cant run a C# 

### ISSUE THREAD

**Issue by OmarElgendi** [dotnet/website-feedback#141]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

x64

### Description

i downloaded and installed the .NET 8 SDK 
and Download and install VS Code 
and then Opened VS Code and selected the Extensions button in VS Code's Activity Bar to the left.and Typed C# in the search bar, select C# Dev Kit, and then selected the Install button on the C# Dev Kit extension page.
and then selected Terminal, then New Terminal.
but i got error

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was    
included, verify that the path is correct and try again.
At line:1 char:1

**Comment by mairaw** [comment]
Have you tried restarting VS Code? If you type `dotnet --info` on a terminal outside of VS Code (command prompt or powershell), does it still say that that dotnet was not recognized?
