### ISSUE TITLE
The computer does not recognize my dotnet

### ISSUE THREAD

**Issue by isaksla** [dotnet/website-feedback#142]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

![compu](https://github.com/dotnet/website-feedback/assets/169577958/51a3e43b-2938-457f-9e73-338809ba7b52)

### Description

I installed it many times and I uninstalled it again because the computer console and the visualstudiocode did not recognize it, I sent them the error that I got, I followed all the steps on the .net page but it doesn't work for me

### dotnet --info

C:\>dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.32
  Commit:  f94bb2c3ff

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
I think you have an issue with PATH based on the information you shared above. Your computer is x64 and it's showing .NET runtimes in the x86 folder.

You can double check by typing `where.exe dotnet` on command prompt or powershell to see what it returns. If x86 comes first, you should follow the instructions at https://github.com/dotnet/core/issues/5962#issuecomment-780084535.

Let me know if that helps.
