### ISSUE TITLE
.NET

### ISSUE THREAD

**Issue by montelowillah** [dotnet/website-feedback#144]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

windows

### More information about your system

x64

### Description

I Cannot create a new .NET project in my visual studio code

### dotnet --info

C:\Windows\system32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.422
 Commit:    ae2bd4ec54

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.422\

global.json file:
  Not found

Host:
  Version:      6.0.30
  Architecture: x64
  Commit:       97d8f4cade

.NET SDKs installed:
  6.0.422 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

C:\Windows\system32>

**Comment by mairaw** [comment]
What error do you get? From the information above, it seems you haven't installed .NET 8 SDK, only .NET 6. Can you make sure .NET 8 is installed?
