### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ajheskett** [dotnet/website-feedback#145]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

Windows 10.0.22631, x64

### Description

Getting the error 0x80070652 another installation is already in progress. What installation and how can i find it and see why it is stuck? 

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet --info
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
Have you tried restarting VS Code or your machine?

Does `dotnet --info` work if you run in a command prompt or powershell window?

**Comment by ajheskett** [comment]
See I’m trying to play baldurs gate, and it redirects me to needing to
install .NET 6.0 Desktop Runtime, but whenever I attempt to install that it
has an error catch because of another installation in progress. Been doing
this for a couple days. Just wanna know where I can find the current
installations.

**Comment by mairaw** [comment]
Were you able to solve your issue?
