### ISSUE TITLE
.net

### ISSUE THREAD

**Issue by Nourgalal** [dotnet/website-feedback#146]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### More information about your system

x64

### Description

localhost uses encryption to protect your information. When Microsoft Edge tried to connect to localhost this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be localhost, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Microsoft Edge stopped the connection before any data was exchanged.

You can't visit localhost right now because the website sent scrambled credentials that Microsoft Edge can't process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by mairaw** [comment]
Can you share a screenshot? Is this about the NET::ERR_CERT_INVALID error message?
