### ISSUE TITLE
Problem with .NET: New Project

### ISSUE THREAD

**Issue by Otaviokd** [dotnet/website-feedback#147]
### URL

https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

Operating System: 64-bit operating system, x64-based processor

Edition: Windows 10 Pro Education
Version: 22H2
OS Build: 19045.4412
Experience: Windows Feature Experience Pack 1000.19056.1000.0

### Description

![DOTNET](https://github.com/dotnet/website-feedback/assets/112825087/d2dc2d70-b844-42ac-8e37-34be0516b9e3),

### dotnet --info

.NET SDK:

Version: 8.0.300
Commit: 326f6e68b2
Workload version: 8.0.300-manifests.c1c70047
MSBuild version: 17.10.4+10fbfbf2e

Runtime Environment:

OS Name: Windows
OS Version: 10.0.19045
OS Platform: Windows
RID: win-x64
Base Path: C:\Program Files\dotnet\sdk\8.0.300\

Installed .NET Workloads:
No workloads installed to display.
Host:

Version: 8.0.5
Architecture: x64
Commit: 087e15321b
.NET SDKs installed:

8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
None

Environment variables:
Not set

global.json file:
Not found

**Comment by mairaw** [comment]
Do you have more information on the error or is this all that is shown?
Have you tried restarting VS Code?

@timheuer @webreidi any other ideas?

**Comment by webreidi** [comment]
It would be helpful to get the information that is printed in the Output pane for C# Dev Kit.

**Comment by Otaviokd** [comment]
I was just following the tutorial and got the terror, Already installed, uninstalled,  restarted.

**Comment by mairaw** [comment]
@Otaviokd seria ótimo ter a mensagem de erro que aparece na janela de output no VS Code. Ia ajudar o nosso time a analisar o erro.

**Comment by Otaviokd** [comment]
isso aqui?

Error occurred in readTelemetryFileAsync: undefined
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Using preinstalled .NET runtime at "C:\Program Files\dotnet\dotnet.exe"
Failed to find dotnet from path: Error: Error: spawn where ENOENT
STDOUT:

STDERR:

.NET server started and IPC established in 5621ms
Completed Spawn .NET server (13663ms)
Completed Clear environment (15247ms)
Completed Open a solution with environment service (15526ms)
Starting Restore solution...
Selected configuration: null, active configuration: Debug|Any CPU
Completed Open a solution (15533ms)
Starting NuGet restore for the solution.
Starting command: "dotnet.exe" restore C:\Users\Pc Sena\Desktop\Otávio\Vscode\Vscode.sln --interactive...
Completed command: "dotnet.exe" restore C:\Users\Pc Sena\Desktop\Otávio\Vscode\Vscode.sln --interactive (9514ms)
Completed NuGet restore.
Completed Restore solution (9521ms)
Failed to find dotnet from path: Error: Error: spawn where ENOENT
STDOUT:

STDERR:

**Comment by smitpatel** [comment]
Root cause here: where command is not found on system. We have a fix for this in progress.

**Comment by mairaw** [comment]
@smitpatel do you have a tracking issue?

**Comment by smitpatel** [comment]
@mairaw - https://github.com/microsoft/vscode-dotnettools/issues/1153
