### ISSUE TITLE
Build Failures on Mac M1

### ISSUE THREAD

**Issue by willytenggara** [dotnet/website-feedback#148]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### More information about your system

ARM64

<img width="281" alt="Screenshot 2024-05-21 at 09 57 46" src="https://github.com/dotnet/website-feedback/assets/73949831/d16214b6-ae15-4fb4-a125-dadba995d78b">

### Description

Build just failed when I run the project

**Comment by mairaw** [comment]
Can you share the build error messages that you're getting? Can you also type `dotnet --info` on a terminal and share the results?

**Comment by willytenggara** [comment]
It's all good. It works as expected. Thanks!

**Comment by mairaw** [comment]
Good to hear. Closing the issue then.
