### ISSUE TITLE
When I try to create MyConsoleApp is says "Creating Templeate failed"

### ISSUE THREAD

**Issue by ValK04** [dotnet/website-feedback#149]
### URL

https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

x64

### Description

I have windows and Im trying to do the steps that sais the .Net web to do it. But when i tried to do the MyConsoleApp it says this
![Captura de pantalla 2024-05-21 140124](https://github.com/dotnet/website-feedback/assets/167036166/22851e05-0347-4450-9ee4-a539d3dcdec1)
Wat should i do?

### dotnet --info

SDK DE .NET:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.c1c70047
 MSBuild version:   17.10.4+10fbfbf2e

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

Cargas de trabajo de .NET instaladas:
No hay cargas de trabajo instaladas para mostrar.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Do you have more information on the error or is this all that is shown?
Have you tried restarting VS Code?

@timheuer @webreidi any other ideas?

**Comment by ValK04** [comment]
Yes i tried several times. I try to follow everything on the web. But i it
says error in the temolate. I say something about a password on the  page.
It can be that?

**Comment by smitpatel** [comment]
> I say something about a password on the  page.

Can you elaborate more on that?

Can you verify that the folder where you are trying to create the project either doesn't exist or empty?
Can you also share logs? To do so,
Open extension logs folder and provide content of ms-dotnettools.csdevkit folder
![image](https://github.com/dotnet/website-feedback/assets/1528107/b60edd66-e6a8-4dbd-9ca9-028471424c1c)
![image](https://github.com/dotnet/website-feedback/assets/1528107/e373465a-c3b8-407a-863d-db47d5d18218)

**Comment by ValK04** [comment]
[image: image.png]

**Comment by ValK04** [comment]
[image: image.png]

**Comment by smitpatel** [comment]
Can you upload the content ms-dotnettools.csdevkit folder as zip file?
