### ISSUE TITLE
uBlock blocks feedback on tutorials

### ISSUE THREAD

**Issue by ryank425** [dotnet/website-feedback#15]
https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install#

I am using Windows 10 21H1 (OS Build 19043.1348) with Edge Version 96.0.1054.43 (Official build) (64-bit) 

If you click "I ran into an issue" button, and click "Provide Feedback" button, the page just scrolls up and down and nothing happens.

The button works normally only when the "Feedback" button on the right side next to the vertical scroll bar appears.

I think the correct behavior should be that "Provide Feedback" button being disabled until loading or the new component with loading placeholder shows up to load Feedback module.

**Comment by mairaw** [comment]
Related to #4

**Comment by mairaw** [comment]
We have since implemented some logic to display a link for feedback if there's an ad blocker.
