### ISSUE TITLE
Sdk Missing 

### ISSUE THREAD

**Issue by swapnil-siingh** [dotnet/website-feedback#151]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### More information about your system

Windows 11 x64

### Description

![image](https://github.com/dotnet/website-feedback/assets/111067743/1761a508-b3bd-4119-a9e0-d086aaec6de7)
Environment variables are not set, help me!

### dotnet --info

Host:
  Version:      8.0.5
  Architecture: x86
  Commit:       087e15321b
  RID:          win-x86

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
You indicated that your system is x64 but your dotnet --info shows it's trying to execute the x86 and that it has found other architectures. I think this is a problem with PATH.

Type the command `where.exe dotnet` and see if x86 is returned first. If so, follow the instructions at https://github.com/dotnet/core/issues/5962#issuecomment-780084535.

**Comment by swapnil-siingh** [comment]
It Worked! Thankyou For your Help.

**Comment by mairaw** [comment]
Great to hear!
