### ISSUE TITLE
not able to create new ,net project

### ISSUE THREAD

**Issue by eshank14** [dotnet/website-feedback#152]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

windows 10 x64

### Description

after selecting the name for the console app and its directory 
it shows an error 
![image](https://github.com/dotnet/website-feedback/assets/170557372/805d83df-f7b2-4cb7-a8ba-2bc3fea397d4)

### dotnet --info

PS C:\Program Files (x86)\Microsoft.NET> dotnet --info  
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.c1c70047
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\      

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Do you have more information on the error or is this all that is shown?
Have you tried restarting VS Code?

@timheuer @webreidi any other ideas?

**Comment by webreidi** [comment]
It would be helpful to get the information that is printed in the Output pane for C# Dev Kit.

**Comment by eshank14** [comment]
you see, I was trying to make a new project (my first one), so after doing all the steps in the tutorial from the .NET website 
![image](https://github.com/dotnet/website-feedback/assets/170557372/127e0261-f2a4-4b4c-a1c9-ab14757b46ae)
I got the above mentioned error

And these are all the outputs that I've got till now
PS C:\Program Files (x86)\Microsoft.NET> dotnet

  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.     

path-to-application:
  The path to an application .dll file to execute.      
PS C:\Program Files (x86)\Microsoft.NET> dotnet --info  
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.c1c70047
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\      

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by smitpatel** [comment]
Can you verify that the folder where you are trying to create the project either doesn't exist or empty?
Can you also share logs? To do so,
Open extension logs folder and provide content of ms-dotnettools.csdevkit folder
![image](https://github.com/dotnet/website-feedback/assets/1528107/b60edd66-e6a8-4dbd-9ca9-028471424c1c)
![image](https://github.com/dotnet/website-feedback/assets/1528107/e373465a-c3b8-407a-863d-db47d5d18218)

**Comment by kvenkatrajan** [comment]
@eshank14 is it possible to provide the details that @smitpatel asked above (especailly the logs) please? That would help us assist you better. Thanks in advance!
