### ISSUE TITLE
command .net new project doesn't work.

### ISSUE THREAD

**Issue by BreadSoul** [dotnet/website-feedback#154]
### URL

https://dotnet.microsoft.com/ru-ru/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

Windows 11, 64 bit, VSC.

### Description

Hellow. When I try to write in the search of Visual Studio Code: ">.NET: New Project", I get an error: "Command '.NET: New Project...' resulted an error". I tried to use terminal "dotnet new console", but I got an error: 
"The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application 'new' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found."

I have already installed .NET from official site, c# and c# dev Kit from VSC. Help me, please.

### dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x86
  Commit:       5a400c212a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by mairaw** [comment]
You indicated that your system is x64 but your dotnet --info shows it's trying to execute the x86 and that it has found other architectures. I think this is a problem with PATH.

Type the command `where.exe dotnet` and see if x86 is returned first. If so, follow the instructions at https://github.com/dotnet/core/issues/5962#issuecomment-780084535.

Let me know if this solves your issue!

**Comment by BreadSoul** [comment]
I tried to do it but nothing changes. When I write: "where.exe dotnet" I get "C:\Program Files\dotnet\dotnet.exe
C:\Program Files (x86)\dotnet\dotnet.exe". Help me, please.

**Comment by mairaw** [comment]
Can you share the version of VS Code and where did you run the command `dotnet --info`? Because where you ran that command is a x86 arch, so it's not finding the SDK.

adding @webreidi @smitpatel to see if they have other suggestions

**Comment by smitpatel** [comment]
Based on output, it looks like only .NET runtime is installed on the machine not SDK.
