### ISSUE TITLE
Issue while running the .net app

### ISSUE THREAD

**Issue by omarwaheed22** [dotnet/website-feedback#159]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

macos

### More information about your system

I am on MacOS 14.5, and the architecture im guessing is ARM64 and im using an M1 MacBook Air

### Description

I ran the dotnet watch code and unfortunately i recieved this error and as im new to this program im not really sure where i should go from here, any input would be helpful, i did install it a couple of times so im gonna try deleting the other files and seeing if that was the issue but just in case it isnt here is the error code:

/Users/omar/BlazorApp/BlazorApp/BlazorApp/Components/App.razor(16,5): error RZ9985: Multiple components use the tag 'Routes'. Components: BlazorApp.BlazorApp.BlazorApp.Components.Routes, BlazorApp.Components.Routes [/Users/omar/BlazorApp/BlazorApp.csproj]
/Users/omar/BlazorApp/BlazorApp/Components/App.razor(16,5): error RZ9985: Multiple components use the tag 'Routes'. Components: BlazorApp.BlazorApp.Components.Routes, BlazorApp.Components.Routes [/Users/omar/BlazorApp/BlazorApp.csproj]
/Users/omar/BlazorApp/BlazorApp/Program.cs(3,1): error CS8802: Only one compilation unit can have top-level statements. [/Users/omar/BlazorApp/BlazorApp.csproj]
/Users/omar/BlazorApp/Program.cs(3,1): error CS8802: Only one compilation unit can have top-level statements. [/Users/omar/BlazorApp/BlazorApp.csproj]

### dotnet --info

.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: arm64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by omarwaheed22** [comment]
Yeah im dumb deleting the files and just letting it make it again and there being only one of it worked, sorry for whoevers time i might waste whoops

**Comment by mairaw** [comment]
Sorry it took us so long to get back to you. Have you managed to get it working?

**Comment by omarwaheed22** [comment]
Yeah I did😅😅😅thanks for replying tho😊
