### ISSUE TITLE
SSL Error, installed suggested ssl certifcates from Visual Studio

### ISSUE THREAD

**Issue by saurabhg31** [dotnet/website-feedback#160]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### Description

When debugging C# Blazor app for first time after creating new project show SSL invalid in chrome (https://localhost:7194/)

**Comment by katiesavage** [comment]
Can you send a screenshot of the error message that you're seeing?
