### ISSUE TITLE
Command '.NET: New Project...' resulted in an error Unable to get dotnet information to initialize template engine host

### ISSUE THREAD

**Issue by timeeah** [dotnet/website-feedback#161]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

macos

### Description

Not able to continue after selecting .NET new project in the search bar hence :
Command '.NET: New Project...' resulted in an error Unable to get dotnet information to initialize template engine host

### dotnet --info

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

**Comment by CodeHeroJake** [comment]
Check if the .NET SDK is installed.
I just met the same problem. I just installed the .Net-Runtime package, but not .Net SDK.
After installing .Net SDK., everything runs normaly ! 
May we met the same problem, And you can try it.

**Comment by katiesavage** [comment]
@timeeah can you confirm if you installed the .NET 8 SDK? Can you run `dotnet --info` in your terminal and send the result?
