### ISSUE TITLE
Localhost error

### ISSUE THREAD

**Issue by kmr313** [dotnet/website-feedback#164]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run

### Operating system

windows

### More information about your system

windows 10 x64
managed machine but i have admin rights

### Description

i got the below error after i ran the code
ERROR: No webpage was found for the web address: http://localhost:5090

### dotnet --info

C:\apache-maven-3.8.7\MyMicroservice\MyMicroservice>dotnet run
Building...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5090
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\apache-maven-3.8.7\MyMicroservice\MyMicroservice

**Comment by katiesavage** [comment]
Could you try running `dotnet --info` and send the result?

@baronfel any ideas about what may be causing this issue?

**Comment by baronfel** [comment]
Nope, no clue. The output suggests things are working just fine, so perhaps someone from AspNet might have more triage steps.

**Comment by mairaw** [comment]
The address they have to navigate to should look like http://localhost:<port number>/weatherforecast, so in this case http://localhost:5090/weatherforecast. 

We could potentially add the Got an error section on this step because it's a common problem.
