### ISSUE TITLE
Cannot open web page in Edge due to certificate issue

### ISSUE THREAD

**Issue by sphccatcadmin** [dotnet/website-feedback#166]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### More information about your system

Windows 11 Pro x64

### Description

Your connection isn't private
Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards).
NET::ERR_CERT_INVALID
localhost uses encryption to protect your information. When Microsoft Edge tried to connect to localhost this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be localhost, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Microsoft Edge stopped the connection before any data was exchanged.

You can't visit localhost right now because the website sent scrambled credentials that Microsoft Edge can't process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by katiesavage** [comment]
Could you try the "Got an error?" instructions at the bottom of the page: 
![image](https://github.com/user-attachments/assets/3748a5b0-93af-4086-afc3-a9da35d8e620)

Let me know if this fixes it.
