### ISSUE TITLE
unsafe code isue showing When Installing Entity Framework in VS 2022 .net core

### ISSUE THREAD

**Issue by pravin9696** [dotnet/website-feedback#168]
### URL

![image](https://github.com/dotnet/website-feedback/assets/88921921/a1c0685d-fda5-4264-9bc6-cfcd60948e37)

### Operating system

windows

### Description

I am creating .net core project in 8.0 framework. when I am trying to install Entity frame workcore.sqlserver version 8.0  It is showing following error

Microsoft.Win32.SystemEvents doesn't support $(TargetFramework). Consider updating your TargetFramework to netcoreapp3.1 or later.

**Comment by mairaw** [comment]
This is not really related to a tutorial but we can try to help you.

Can you share the contents of your csproj file?
