### ISSUE TITLE
Wrong Docker metadata

### ISSUE THREAD

**Issue by simonedibilio** [dotnet/website-feedback#169]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image

### Operating system

Arch Linux

### More information about your system

- EndeavourOS
- x64

### Description

In the "Add Docker metadata" section of the tutorial, you typed "COPY MyMicroservice.csproj ." instead of "COPY MyMicroService.csproj .".

That breaks the build.

Fix for future users, please :)

### dotnet --info

.NET SDK:
 Version:           8.0.106
 Commit:            ab2d260803
 Workload version:  8.0.100-manifests.8f6aae10
 
Runtime Environment:
 OS Name:     endeavouros
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.106/
 
.NET workloads installed:
 Workload version: 8.0.100-manifests.8f6aae10
There are no installed workloads to display.
 
Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e
 
.NET SDKs installed:
  8.0.106 [/usr/share/dotnet/sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
  https://aka.ms/dotnet/info
 
Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
I believe the tutorial uses "MyMicroservice" as the service name throughout (see [Create your service](https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create)). Do you know if you named the service "MyMicroService" or "MyMicroservice"?
