### ISSUE TITLE
Template code does not run

### ISSUE THREAD

**Issue by mikeries** [dotnet/website-feedback#17]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Updated VS to 17.8.6
Created a new project using the 'Blazor Web App' project template.
![image](https://github.com/dotnet/core/assets/17058254/29c567c9-4fd3-4311-89ef-765311372ada)

![image](https://github.com/dotnet/core/assets/17058254/e9c54d97-32c2-418c-ba42-c5a9b53b9c38)

Click Run button. Project doesn't run correctly.
![image](https://github.com/dotnet/core/assets/17058254/33d4bb33-9434-4260-ad77-c91b9c92323b)

**Comment by danroth27** [comment]
OK, no worries! It's good to hear things are now working for you. If you see this issue again, please let us know and we'll try to figure out what's going on.
