### ISSUE TITLE
Command .Net: New Proyect ... Resulted in an error

### ISSUE THREAD

**Issue by Alejo96c** [dotnet/website-feedback#170]
### URL

https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

Windows 11, sistema operativo de 64 bits, procesador basado en x64 

### Description

estoy en la parte donde doy el comando dotnet, todo bien, pero cuando paso a la parte de terminal, new terminal le doy >.Net: New proyect me sale ese error y no me deja seguir 

### dotnet --info

PS C:\Users\USUARIO> dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
PS C:\Users\USUARIO>

![Captura de pantalla 2024-06-11 222023](https://github.com/dotnet/website-feedback/assets/172462242/1710e66b-96d5-4a20-8cbf-836ffdf0193d)

**Comment by katiesavage** [comment]
What result do you see when you type `dotnet --info` ?
