### ISSUE TITLE
SKIBIDI AH SKIBIDI SKIBIDIII AHHHHHHHHHHHHHHHHHHHHH

### ISSUE THREAD

**Issue by Imrande** [dotnet/website-feedback#171]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install MRS

### Operating system

windows 10

### More information about your system

SKIBIDIIIIIIIIIIIIIIII

### Description

SKIBIDIIIIIIIIIIIIIIII

### dotnet --info

Real_Imrandemir

**Comment by mairaw** [comment]
Closing since no actual feedback was provided,
