### ISSUE TITLE
Blazor App in Solution explorer doesnt show any files after creating the project

### ISSUE THREAD

**Issue by 4gopi** [dotnet/website-feedback#174]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### More information about your system

Windows 10 Pro 64 bit

### Description

After creating the project solution explorer doesn't show any files.
Even after installing the SDK 8.0.302 

### dotnet --info

Host:
  Version:      8.0.5
  Architecture: x86
  Commit:       087e15321b
  RID:          win-x86

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]
Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
To clarify, are you using Visual Studio for the tutorial? If so, what version of Visual Studio are you using?

**Comment by mairaw** [comment]
The `dotnet --info` results above show that you might have an issue with PATH since it shows it's running on x86 RID and you have a 64-bit machine.

Type the command where.exe dotnet and see if x86 is returned first. If so and your system is x64, follow the instructions at https://github.com/dotnet/core/issues/5962#issuecomment-780084535.

Let me know if this solves your issue!
