### ISSUE TITLE
Found markup element with unexpected name - Mac

### ISSUE THREAD

**Issue by tkoolhoven2** [dotnet/website-feedback#176]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

macos

### More information about your system

Ventura 

### Description

In the out of the box code example on the Mac, I keep getting "Found markup element with unexpected name". Example, for the component PageTitle there is a squiggle line under the component name on Home.razor in the Pages directory.

### dotnet --info
SDK 8

_No response_

**Comment by tkoolhoven2** [comment]
I managed to downgrade the C# Base language support extension to V2.22.5. You can do this by clicking the uninstall option and selecting the appropriate version on the C# extension. This corrects the issue. Although, I feel downgrading is not a solution.

**Comment by mairaw** [comment]
Are you getting this in VS Code? 

@webreidi @danroth27

**Comment by danroth27** [comment]
@phil-allen-msft @leslierichardson95 Have we seen any other similar reports for Razor in VSCode on macOS?

@tkoolhoven2 Can you confirm which VS Code C# extension versions you tested with? I believe the latest version of the C# extension for VS Code is currently v2.34.12. Are you saying that when you try to use this latest version you ran into this issue?

**Comment by tkoolhoven2** [comment]
> Are you getting this in VS Code?
> 
> @webreidi @danroth27

Yes, I'm getting this in VS Code.
