### ISSUE TITLE
error create blazor app

### ISSUE THREAD

**Issue by frankreyesgarcia** [dotnet/website-feedback#177]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

macos

### More information about your system

<img width="514" alt="image" src="https://github.com/dotnet/website-feedback/assets/125555252/e242138a-b4c5-4251-a0ad-81b19896e73d">

### Description

<img width="514" alt="image" src="https://github.com/dotnet/website-feedback/assets/125555252/fac21086-3dbc-4983-a09d-e20ba981bbf2">

**Comment by mairaw** [comment]
Can you share the `dotnet --info` information so we can see if you have the right prereqs installed?
