### ISSUE TITLE
New Project Issues

### ISSUE THREAD

**Issue by sangayjojo** [dotnet/website-feedback#179]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/createad <html>
<body>

csdevkit.addNewProject
--

<br class="Apple-interchange-newline">
</body>
</html>
![Screenshot (1)](https://github.com/dotnet/website-feedback/assets/173852663/ada0b8ca-8a0f-4154-b75b-55777d382555)

### Operating system

windows

### More information about your system

idid
![Screenshot (1)](https://github.com/dotnet/website-feedback/assets/173852663/caac6a77-5024-43ba-80de-94de0b2799f8)
 everthing as told in the video and it said sdevkit.addNewProject not found

### Description

there was issues with new project

**Comment by mairaw** [comment]
Can you share a screenshot of what version of the C# Dev Kit extension you have installed?

@webreidi @smitpatel any other suggestions?

**Comment by smitpatel** [comment]
Can you check this [FAQ](https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_why-isnt-c-dev-kit-activating-c-dev-kit-commands-are-not-found) and verify if you are not running into one of the mentioned issues.
