### ISSUE TITLE
Error when creating a new project С#

### ISSUE THREAD

**Issue by stnikan** [dotnet/website-feedback#180]
### URL

https://dotnet.microsoft.com/ru-ru/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### Description

![image](https://github.com/dotnet/website-feedback/assets/141735170/3e6e1828-0504-494e-b9cd-ee9ad35fee3e)

### dotnet --info

PS D:\My_github\test_provod\Wire-Tester-user-interface> dotnet --info

Host (useful for support):
  Version: 5.0.17
  Commit:  6a98414363

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mairaw** [comment]
You most likely were having an issue with PATH. Here's another possible solution to fix this:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

I'm glad it's working now.
