### ISSUE TITLE
Components and Weather pages not displaying properly

### ISSUE THREAD

**Issue by t-graceliou** [dotnet/website-feedback#185]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/try

### Operating system

windows

### Description

When I try to visit the counter and weather pages, the localhost link changes (/counter or /weather), but the page itself stays on the Home/Hello World page.

### dotnet --info

.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.ca8b4b2d
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.302\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.10.35013.160
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
Can you confirm that when you navigate to Components/Pages/Counter.razor in your application, it matches the code shown [here](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/try)?

@danroth27 any other ideas?

**Comment by danroth27** [comment]
@t-graceliou Can you share the project with us? Also, do you see any errors in the console output or in the browser dev console?

@mkArtakMSFT Have we seen any issues similar to this one in the past few months?
