### ISSUE TITLE
Problem in running the Tutorial

### ISSUE THREAD

**Issue by Rajbir3** [dotnet/website-feedback#187]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

windows

### Description

The Solution Explorer did not appear. 
The Start Debugging and Run Without Debugging did not respond as expected. Instead, these commands opened the Welcome window. I don't yet know how to go ahead further.

**Comment by katiesavage** [comment]
Can you confirm that you installed the .NET SDK as instructed in step 1?
 If so, have you tried restarting VS Code? 

Can you try clicking on the Program.cs file to see if this triggers the Solution Explorer to appear?
