### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by Hxdeax** [dotnet/website-feedback#188]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows 10

### Description

Whenever i type dotnet this thing pops up

### dotnet --info

 C:\Users\> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by oyvindmtmu** [comment]
Yeah i got this error too. Apparently installing Visual Studio and the .NET workload thingies doesn't also install .NET. 

You'll have to click the download button on [dot.net](https://dotnet.microsoft.com/en-us/) and install it.

**Comment by katiesavage** [comment]
Can you confirm that you installed the .NET SDK as instructed in [step 1](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install)?
If so, have you tried restarting VS Code? And can you check if you can run the command on a standalone PowerShell or command prompt window outside of VS Code? If it works outside VS Code, try restarting your computer.
