### ISSUE TITLE
Error a crear proyecto Blazor

### ISSUE THREAD

**Issue by Nivia17** [dotnet/website-feedback#189]
### URL

https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### More information about your system

x64

### Description

Se encontraron uno o varios errores al crear el proyecto BlazorApp1.

El contenido del proyecto generado puede estar incompleto.

El sdk "Microsoft.NET.Sdk.Web" especificado no se pudo encontrar.

c:\Users\nivia\source\repos\BlazorApp1\BlazorApp1\BlazorApp1.csproj

Por otro lado, al darle aceptar a la ventana de error se abre un proyecto con el "explorador de soluciones" vació

### dotnet --info

C:\Users\nivia>dotnet --information
The command could not be loaded, possibly because:
  * You intended to execute a .NET application:
      The application '--information' does not exist.
  * You intended to execute a .NET SDK command:
      No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

C:\Users\nivia>

**Comment by mairaw** [comment]
¿Puede escribir dotnet --info en lugar de dotnet --information?
