### ISSUE TITLE
Blazor Web App Template not found

### ISSUE THREAD

**Issue by Pawan1718** [dotnet/website-feedback#19]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Blazor Web App Template not found in Visual Studio 2022

**Comment by masteroleary** [comment]
Same

**Comment by mairaw** [comment]
@masteroleary what version of VS you're using?

**Comment by masteroleary** [comment]
17.19.2

**Comment by mairaw** [comment]
@masteroleary Ok, so your VS version is fine. Can you open a command prompt window and tell us what `dotnet --info` returns?

/cc @danroth27

**Comment by masteroleary** [comment]
$ dotnet --info
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.91505830

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-arm64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
 [wasm-tools-net7]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.2\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net6]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.2\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    8.0.6/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.6\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.2\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.9.34622.214
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.2
  Architecture: arm64
  Commit:       1381d5ebd2

.NET SDKs installed:
  7.0.402 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet\x64]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

dev@PARALLELSM2 E:\
$

**Comment by mairaw** [comment]
@masteroleary thanks for the information so far. it seems you're running this on Parallels on a mac, correct?
I wonder if in your case it might be an issue with the PATH. Can you check what `where.exe dotnet` returns?
Maybe you need to change the order like I show at https://github.com/dotnet/core/issues/5962#issuecomment-780084535

I'd also try the CLI version to see if there's a mismatch between what you're running on the terminal and VS.
Can you run the command from https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/create just fine?

**Comment by masteroleary** [comment]
where.exe dotnet
C:\Program Files\dotnet\dotnet.exe

$ dotnet new blazor -o BlazorApp
The template "Blazor Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/8.0-third-party-notices for details.

Processing post-creation actions...
Restoring E:\BlazorApp\BlazorApp.csproj:
  Determining projects to restore...
  Restored E:\BlazorApp\BlazorApp.csproj (in 35 ms).
Restore succeeded.

<img width="1257" alt="Screenshot 2024-03-07 at 7 30 13 AM" src="https://github.com/dotnet/website-feedback/assets/476827/11042a56-2c68-4d59-8a15-aded87082919">
<img width="1251" alt="Screenshot 2024-03-07 at 7 30 23 AM" src="https://github.com/dotnet/website-feedback/assets/476827/65cbf5b9-4fc8-4d35-b00c-2a8d4ef28195">

**Comment by mairaw** [comment]
@masteroleary I checked with the team and they recommended you turn tracing on

Open a developer command prompt and set the following environment variables
SET VS_WTE_DIAGNOSTIC_MODE=File
SET VS_WTE_DIAGNOSTIC_VERBOSITY=2
SET VS_WTE_DIAGNOSTIC_TRACESWITCHES=ALL
SET VS_WTE_DIAGNOSTIC_OUTPUTFILE=%temp%\wte.log
2. Launch VS from the prompt using devenv.exe
3. Do File/New Project so you'll go through the new project dialog
4. Send us the log from %temp%\wte.logor share it, but scrub things like user names from the path

Tracing will log how the template engine is resolving .NET templates, including those coming from optional workloads.

**Comment by masteroleary** [comment]
[03-08-2024 01:52:15.45614] [Trace] SHAREDTRACING: Settings Manager -- global -- BEGIN: Settings Manager Configuration File
[03-08-2024 01:52:15.46114] [Trace] SHAREDTRACING: Settings Manager -- global -- END: Settings Manager Configuration File
[03-08-2024 01:52:15.50699] [Trace] SHAREDTRACING: DotNetOptionalSdkTemplateProvider -- OnGetAllTemplatePackagePathsAsync -- Finding sdk version for 17.9
[03-08-2024 01:52:15.51262] [Trace] SHAREDTRACING: DotNetOptionalSdkTemplateProvider -- OnGetAllTemplatePackagePathsAsync -- sdk version: 8.0.200, dotnet root path: C:\Program Files\dotnet\x64
[03-08-2024 01:52:15.54459] [Trace] SHAREDTRACING: DotNetOptionalSdkTemplateProvider -- OnGetAllTemplatePackagePathsAsync -- template packages: 
[03-08-2024 01:52:15.55409] [Trace] SHAREDTRACING: AggregateTemplatePackageProvider.FinalizePackages --  -- Templates to install: C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.common.itemtemplates.7.0.306.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.common.projecttemplates.7.0.7.0.306.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.test.projecttemplates.7.0.1.1.0-rc.23213.1.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.web.itemtemplates.7.0.7.0.9.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.web.projecttemplates.7.0.7.0.9.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.web.spa.projecttemplates.7.0.7.0.9.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.winforms.projecttemplates.7.0.9-servicing.23321.6.nupkg,C:\Program Files\dotnet\x64\templates\7.0.9\microsoft.dotnet.wpf.projecttemplates.7.0.9-servicing.23321.9.nupkg,c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\web tools\azure\templates\Microsoft.Azure.WebJobs.CSharp.17.9.2.nupkg,c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\web tools\azure\templates\Microsoft.Azure.WebJobs.VisualBasic.17.9.2.nupkg,c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\web tools\azure\templates\Microsoft.WebTools.Http.Template.17.9.2.nupkg,c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\templateengine\Microsoft.VisualStudio.TemplateEngine.FallbackHostData.17.9.197.nupkg
[03-08-2024 01:52:15.56011] [Trace] SHAREDTRACING: TemplateProviderBase.OnGetContentETagAsync -- .NET Core Item Template Provider -- returned: c5d2a47b3d517b83099dfba7aa136c42e6990422e399f8f7d7871f12fac96394
[03-08-2024 01:52:15.56011] [Trace] SHAREDTRACING: TemplateProviderBase.OnGetContentETagAsync -- .NET Core Template Provider -- returned: c5d2a47b3d517b83099dfba7aa136c42e6990422e399f8f7d7871f12fac96394

**Comment by joeloff** [comment]
VS is picking up the templates from Program Files\dotnet\x64. That is used by the x64 copy of dotnet on arm64 machines, and it's picking up older 7.0.9 templates from there.

Are you running an x64 copy of Visual Studio on arm64 Windows?

**Comment by masteroleary** [comment]
> VS is picking up the templates from Program Files\dotnet\x64. That is used by the x64 copy of dotnet on arm64 machines, and it's picking up older 7.0.9 templates from there.
> 
> Are you running an x64 copy of Visual Studio on arm64 Windows?

I am not sure how to tell that. It's quite possible. I moved from a Macbook with an i9 to a Macbook with an M2. Can you offer instructions on how to determine that or how to remove the x64 version and install the correct version?

**Comment by joeloff** [comment]
Awesome, happy to help.

**Comment by mairaw** [comment]
Thanks @joeloff for taking us to the finish line! 

@Pawan1718 the original issue is from you and your case is probably different than @masteroleary. So please let us know if you can confirm which version of VS you're running.
