### ISSUE TITLE
VS 17.8 Blazor missing and additional components missing

### ISSUE THREAD

**Issue by DrHoneyBear** [dotnet/website-feedback#192]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

windows 10 enterprise 10.0.19045

### More information about your system

windows 10 x64 Enterprise 10.0.19045
visual studio 17.8 LTSC Professional 

### Description

We installed VS Pro 17.8 LTSC installer from MSDN subscription account.
The resultant download was c:\temp\vs_professional.exe
We ran the installer simply as **c:\temp vs_professional.exe**
We selected just ASP.NET and web development workload, To the right, Installation Details listed:

- Visual Studio core editor
- ASP.NET and web development

Included:
- .NET Framework 4.7.2 development tools
- ASP.NET and web development perquisites

Optional:
- .NET Framework 4.8 Development tools
- .NET Framework project and item templates
- .NET profiling tools
- Entity Framework 6 tools
- IntelliCode
- .NET Framework 4.6.2-4.7.1 development tools
- Additional project templates
- .NET Framework 4.8.1 development tools

When installation completes, we tried to create a new project and searched for "blazor". There are no razor or blazor project templates.

We ran the InstallerCleanup.exe and it removed everything as expected. We repeated and observed the same result. We then tried to create an offline install, creating a Layout and running the vs_professional.exe from the Layout folder. We again observed the same result.

Where on earth is Blazor? 

We then ran **dotnet --info** command and noticed .NET 8 was not installed nor any SDK **despite them being checkboxed on the installer's Additional Components screen**. We had checkboxed .NET 8 core, SDK etc. 

We then downloaded **dotnet-sdk-8.0.107-win-x64** and installed that.

Still no Blazor.
? What gives ?

- 

### dotnet --info
.NET SDK:
 Version:           8.0.107
 Commit:            1bdaef7265
 Workload version:  8.0.100-manifests.c915c39d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.107\

.NET workloads installed:
 Workload version: 8.0.100-manifests.c915c39d
There are no installed workloads to display.

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.107 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
Sorry you're running into this issue. Could you type the command `where.exe dotnet` on command prompt or powershell to see what it returns? I want to check if this is a PATH issue. 

@danroth27 any other suggestions?

**Comment by danroth27** [comment]
@DrHoneyBear That is very strange! After you installed the .NET 8 SDK manually, are you at least able to run `dotnet new blazor` from the command-line?
