### ISSUE TITLE
An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

### ISSUE THREAD

**Issue by oluzek** [dotnet/website-feedback#193]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

windows

### More information about your system

An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

### Description

<configuration>
    <system.web>
        <customErrors mode="Off"/>
    </system.web>
</configuration>

### dotnet --info

<configuration>
    <system.web>
        <customErrors mode="RemoteOnly" defaultRedirect="mycustompage.htm"/>
    </system.web>
</configuration>

**Comment by katiesavage** [comment]
Hi, were you successfully able to download Visual Studio and the .NET SDK? Could you run **dotnet --info** command and send the result?
