### ISSUE TITLE
I don't know why, but I hit the command and it doesn't work

### ISSUE THREAD

**Issue by jeanroja** [dotnet/website-feedback#196]
### URL

https://dotnet.microsoft.com/ko-kr/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

I did as I was told, but nothing is working 

### dotnet --info

dotnet Is

**Comment by katiesavage** [comment]
Hello, I need some more information. Did you successfully install the .NET SDK and Visual Studio Code?
