### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by danmatias007** [dotnet/website-feedback#198]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify

### Operating system

macos

### Description

An unhandled exception occurred while processing the request.
InvalidOperationException: No writer was cached for the property 'IncrementAmount' on type 'BlazorApp.Components.Pages.Counter'.
Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForUnknownIncomingParameterName(Type targetType, string parameterName)

### dotnet --info

SDK DE .NET:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

Entorno de tiempo de ejecución:
 OS Name:     Mac OS X
 OS Version:  12.7
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.303/

Cargas de trabajo de .NET instaladas:
No hay cargas de trabajo instaladas para mostrar.

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
To clarify, did you hit this error after clicking the "Hot Reload" button in the "Modify a component" section? 

@danroth27 any idea what may be going on here?

**Comment by danroth27** [comment]
@phil-allen-msft @mkArtakMSFT Have you seen this error before?:

> InvalidOperationException: No writer was cached for the property 'IncrementAmount' on type 'BlazorApp.Components.Pages.Counter'.
Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForUnknownIncomingParameterName(Type targetType, string parameterName)

**Comment by petermorlion** [comment]
For anyone Googling this while developing (locally). I just stopped the application and started it again (I was debugging from in Visual Studio). No idea what caused this, because I didn't change my code in between restarting.
