### ISSUE TITLE
dotnet not recognized by my device.

### ISSUE THREAD

**Issue by kamotsele** [dotnet/website-feedback#199]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

x86

### Description

I am trying to start using C# on my laptop. I installed the .NET software and VSCode but when I type "dotnet" in the terminal, I get an error message saying that it cannot recognize dotnet.

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet --info
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
Did you download the .NET SDK as instructed on that page? If so, maybe try restarting VS Code?
