### ISSUE TITLE
No opportunity to modify install, uninstalled and reinstalled fresh never got the screens to choose anything, no screens even similar to screenshots in doc.

### ISSUE THREAD

**Issue by ABB-McCormick** [dotnet/website-feedback#200]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

windows

### Description

This is enough I'll give up on it and go to something that works as shown, don't really want try to fix it at this point.

### dotnet --info

n/a

**Comment by mairaw** [comment]
I'm sorry to hear that. If you change your mind, please give us more information about the error you're getting.
