### ISSUE TITLE
The term "dotnet" is not recognized

### ISSUE THREAD

**Issue by NguyenHuy2509** [dotnet/website-feedback#203]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

The operating system version is Windows 10
The architecture is x64

### Description

I don't know how to fix this error, I have tried many times and no different results
![Extension_ C# Dev Kit - Visual Studio Code 31_7_2024 10_38_25 AM](https://github.com/user-attachments/assets/0a8bb0c9-9ce1-4262-8dc2-c392edc34857)

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
I'm sorry to hear you're having issues running the dotnet command.

Can you confirm that you installed the .NET SDK as instructed in step #1?
If so, have you tried restarting VS Code? And can you check if you can run the command on a standalone PowerShell or command prompt window?

/cc @webreidi

**Comment by webreidi** [comment]
@NguyenHuy2509 try Ctrl+Shift+P and type "install" and select ".NET: Install New .NET SDK" this will bring up a window that will give you the option to install the latest .NET SDK. Click on the big blue button. This will install the latest version of the SDK onto your system. Once that is done, you might need to reload VS Code again to get everything to sync up. You can do this by Ctrl+Shift+P and then type "Reload". Select "Developer: Reload Window". Then bring back up the terminal and try out your dotnet --info command.


![Image](https://github.com/user-attachments/assets/1802fea6-ab97-42d5-ad1f-ab13afe77b5c)
