### ISSUE TITLE
Plain text extension not found in VS codes

### ISSUE THREAD

**Issue by Kh-wasi** [dotnet/website-feedback#204]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

Edition	Windows 11 Pro
Version	22H2
Installed on	‎7/‎21/‎2024
Device name	Khawaja-Wasi
Processor	Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz   1.10 GHz
Installed RAM	4.00 GB (3.81 GB usable)
System type	64-bit operating system, x64-based processor

### Description

As per the instructions I entered the dotnet command to check for the verification is it properly working but the popup occurs in which it is saying that plain text extension not found.

### dotnet --info

![Uploading Screenshot 2024-08-01 110911.png…]()

**Comment by mairaw** [comment]
Can you try to upload the screenshot again? I think you submitted the issue before the image had finished uploading to GitHub.
