### ISSUE TITLE
unable to click .NET new program

### ISSUE THREAD

**Issue by wanwanmeii** [dotnet/website-feedback#205]
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

x86

### Description

![image](https://github.com/user-attachments/assets/46eb7a75-42ea-4e51-99cb-369f015959ac)

### dotnet --info

root@DESKTOP-NB6VOO2:~# dotnet --info
Error: [/usr/lib/dotnet/host/fxr] does not exist

**Comment by katiesavage** [comment]
Can you confirm that you installed the .NET SDK and VS Code as instructed in [step 1 of the Download section](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install)?
If so, can you try the following:
1. Restart VS Code 
2. Check if you can run the command on a standalone PowerShell or command prompt window outside of VS Code. If it works outside VS Code, try restarting your computer.

Let me know if that works!
