### ISSUE TITLE
ОШибка

### ISSUE THREAD

**Issue by DerryGM** [dotnet/website-feedback#206]
### URL

https://dotnet.microsoft.com/ru-ru/learn/dotnet/hello-world-tutorial/create
![photo_2024-08-05_09-01-34](https://github.com/user-attachments/assets/a6b348e7-3589-4261-8c75-e83ff08ce3f8)

### Operating system

windows

### More information about your system

архитектура х64
Версия ОС

### Description

Откройте палитру команд в VS Code, нажав клавиши CTRL+SHIFT+P.
Введите .NET: , чтобы просмотреть команды, которые можно выполнить с помощью C# Dev Kit!
Найдите и выберите .NET: новый проект, чтобы создать новый проект .NET.
Прокрутите вниз и выберите Консольное приложение.
Выберите расположение папки для сохранения проекта.
При запросе присвойте имя проекту MyConsoleApp в палитре команд.

КОроче когда вот это поворяю ошибку дает
@
![photo_2024-08-05_09-01-34](https://github.com/user-attachments/assets/eb646378-bd54-4339-b934-fb73e07e04b0)

### dotnet --info

Host:
  Version:      7.0.10    
  Architecture: x86       
  Commit:       a6dbb800a4

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]     
  Microsoft.NETCore.App 3.1.22 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS D:\C#\Project>

**Comment by mairaw** [comment]
The dotnet --info results above show that you might have an issue with PATH.

Type the command `where.exe dotnet` and see if x86 is returned first. If so, follow the instructions at https://github.com/dotnet/core/issues/5962#issuecomment-780084535.

Let me know if this solves your issue!
