### ISSUE TITLE
Dotnet

### ISSUE THREAD

**Issue by lDesperatel** [dotnet/website-feedback#207]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

x64

### Description

well im following everything that is said but the only thing that not working is dotnet for some reason?

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.   
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by katiesavage** [comment]
Have you tried restarting VS Code? If you type dotnet --info on a terminal outside of VS Code (command prompt or powershell), does it still say that that dotnet was not recognized?
