### ISSUE TITLE
no .NET: New Project

### ISSUE THREAD

**Issue by petelomax** [dotnet/website-feedback#208]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

W10 x64

### Description

There is no .New: New project option

### dotnet --info

PS C:\Users\petel> dotnet --info
.NET SDK:
 Version:           8.0.303   
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS C:\Users\petel>

**Comment by katiesavage** [comment]
Hi, can you send a screenshot of what you see when you do the following steps inside visual studio code:
1. Open the command palette by pressing *CTRL + SHIFT + P*
2. Type *.NET: New Project*

**Comment by petelomax** [comment]
![vscn](https://github.com/user-attachments/assets/1b734802-6f02-42b3-a4dd-7c5927cd307f)

**Comment by petelomax** [comment]
update:
![vscn](https://github.com/user-attachments/assets/8189a8f2-bc88-43a8-b8d5-0aafe9c01e5a)

**Comment by mairaw** [comment]
Can you confirm if you have the C# Dev Kit installed?

Navigate to Extensions (Ctlr + Shift + X) and type the name of the extension.

Confirm that is installed

![image](https://github.com/user-attachments/assets/367e5b8d-175a-413c-9a09-3499e955fe3f)

**Comment by petelomax** [comment]
OH, apparently not, though I can still run dotnet. I think what happened is some Windows 11 upgrade failed, preventing the PC from booting (twice) and eventually it "rolled back", one/both of which must have clobbered it. The reinstall is in progress.

**Comment by petelomax** [comment]
It's there now, closing this.
