### ISSUE TITLE
No installed .NET SDK was found on the computer

### ISSUE THREAD

**Issue by HannahHopeGreat** [dotnet/website-feedback#209]
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

![下载](https://github.com/user-attachments/assets/d46e4855-7899-44fa-8875-6ee8a8b5fd9a)

### Description

No installed .NET SDK was found on the computer. If it is installed, make sure it can be found through the PATH environment variable. C# Dev Kit does not work without a supported version of SDK. After installing the SDK, you need restart the VS Code session, or the computer.

**Comment by HannahHopeGreat** [comment]
my computer is  X64 Windows 11

**Comment by katiesavage** [comment]
Did you download the .NET SDK from within Visual Studio Code? If so, you may need to restart Visual Studio Code.

If this does not work, can you type dotnet --info into the terminal and send the response?
