### ISSUE TITLE
I found a Problem as described below

### ISSUE THREAD

**Issue by lincoln202** [dotnet/website-feedback#21]
Problem encountered on https://dotnet.microsoft.com/pt-br/learn/aspnet/microservice-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I tryed to install the ISO program but it appear to be wrong.

**Comment by mairaw** [comment]
This issue was closed because there was no response to a request for more information for 10 days.
