### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by elleon775** [dotnet/website-feedback#210]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### Operating system

macos

### More information about your system

wont open on my laptop after ive downloaded a ton of times 

### Description

wont open on my laptop after ive downloaded a ton of times 

### dotnet --info

wont open on my laptop after ive downloaded a ton of times

**Comment by mairaw** [comment]
what won't open @elleon775? what error do you get? what have you downloaded?
