### ISSUE TITLE
I just wanna play baldurs gate 3 man

### ISSUE THREAD

**Issue by sgttyo** [dotnet/website-feedback#211]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

i have no idea wtf any of this means

### Description

i install bg3 on steam and click launch, it tells me dotnet needs to be installed to play. i click the links and go to install dotnet, dotnet gives me an error saying there is already an installation in progress and to finish that. i figure okay, lets go follow the tutorial on how to set it up because idk wtf else to do or how to finish whatever install is in progress even though it was my first time installing. i follow your tutorial, input dotnet into your terminal, and it gives me an error. for the love of god someone teach me how to computer because im losing my mind just trying to play baldurs gate 3.

### dotnet --info

PS C:\Users\xXzam> dotnet
dotnet : The term 'dotnet' is not recognized as the name of a cmdlet,  
function, script file, or operable program. Check the spelling of the  
name, or if a path was included, verify that the path is correct and   
try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], Comma

   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
@sgttyo I'm sorry to hear you're having issues installing .NET. You shouldn't need the tutorial for installing the .NET runtime, this is more for someone who wants to learn how to code.

Does baldur gives you any error message or pop-up when you try to execute?
