### ISSUE TITLE
Certificate issues on Microsoft Edge when running the project for the first time

### ISSUE THREAD

**Issue by felixindynamsoft** [dotnet/website-feedback#215]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### Description

![image](https://github.com/user-attachments/assets/fc45586e-21ac-42de-8c84-18c8bd052606)
![image](https://github.com/user-attachments/assets/786ca9a1-9ee8-4b1a-bfc0-9470fe7178d9)

When running the project for the first time on Microsoft Edge, it shows the error above.
This is after installing the default certificates from following the tutorial and running it for the first time.
This issue doesnt happen with Firefox.

**Comment by katiesavage** [comment]
At the bottom of the page there are some instructions:
*If you receive an error message saying "Your connection is not private" with error code NET::ERR_CERT_INVALID, try to restart all browser windows so the new certificate can be picked up by the browser and run the application again.*

Have you tried this?

**Comment by felixindynamsoft** [comment]
Works now. Thanks!
