### ISSUE TITLE
i can't run new project

### ISSUE THREAD

**Issue by JohnnyDat06** [dotnet/website-feedback#216]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### Description

No installed .NET SDK was found on the computer. If it is installed, make sure it can be found through the PATH environment variable. C# Dev Kit does not work without a supported version of SDK. After installing the SDK, you need restart the VS Code session, or the computer.

### dotnet --info

No installed .NET SDK was found on the computer. If it is installed, make sure it can be found through the PATH environment variable. C# Dev Kit does not work without a supported version of SDK. After installing the SDK, you need restart the VS Code session, or the computer.

**Comment by katiesavage** [comment]
Can you confirm that you installed the .NET SDK and VS Code as instructed in [step 1 of the Download section](https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install)?
If so, have you tried restarting VS Code? And can you check if you can run the command on a standalone PowerShell or command prompt window outside of VS Code? If it works outside VS Code, try restarting your computer.
