### ISSUE TITLE
"dotnet" not working properly

### ISSUE THREAD

**Issue by LTimmy2012** [dotnet/website-feedback#217]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

Can someone help me?
I wrote "dotnet" and it did not  work and it said 

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1

**Comment by katiesavage** [comment]
Can you confirm that you installed the .NET SDK as instructed in step 1?
If so, have you tried restarting VS Code? And can you check if you can run the command on a standalone PowerShell or command prompt window outside of VS Code? If it works outside VS Code, try restarting your computer.
