### ISSUE TITLE
command "dotnet --version" unknowed by the terminal

### ISSUE THREAD

**Issue by nnevedm** [dotnet/website-feedback#219]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

macos

### More information about your system

macOS Monterey 12.7.6
Architecture x64

### Description

I want to install .NET SDK to build a first .NET Application. I did click to install and it's intalled. But now the command "dotnet --version" won't execute on my terminal.

### dotnet --info

➜  ~ dotnet --version
zsh: command not found: dotnet

**Comment by mairaw** [comment]
And did you restart the terminal window after you installed the SDK?

**Comment by nnevedm** [comment]
yes I did

**Comment by baronfel** [comment]
Is the directory `/usr/local/share/dotnet/` present on your mac, and is it on your PATH environment variable? If not, can you add it to your PATH and try running `dotnet --info` again?
