### ISSUE TITLE
Problem create new project returns an error.

### ISSUE THREAD

**Issue by mhutchinson1970** [dotnet/website-feedback#222]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

macos

### More information about your system

OS: Sonoma 14.6.1
Apple M3 Max (arm)

### Description

When I select .Net: New Project, it returns the error "Command '.NET: New Project...' resulted in an error     t is not iterable.

### dotnet --info

marlohutchinson1@Marlos-MacBook-Pro ~ % dotnet --info

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71
  RID:          osx-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  No runtimes were found.

Other architectures found:
  arm64 [/usr/local/share/dotnet]
    registered at [/etc/dotnet/install_location_arm64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
Can you confirm that you installed the .NET SDK and VS Code as instructed in https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install?
If so, can you try restarting VS Code?

Let me know if that works!
