### ISSUE TITLE
didn't find the Blazor  in the create new repo

### ISSUE THREAD

**Issue by dragonayan** [dotnet/website-feedback#223]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### Description

didn't find the Blazor  in the create new repo

**Comment by mairaw** [comment]
if you type blazor, no results are returned?

Can you check if you have the right workloads installed as explained in https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install?
