### ISSUE TITLE
file not found( the system cannot find the specific file)

### ISSUE THREAD

**Issue by NightcoreRagod** [dotnet/website-feedback#224]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add

### Operating system

windows

### Description

built failed during program run time.
![Screenshot 2024-08-26 000849](https://github.com/user-attachments/assets/cb9f17be-fa4c-40d4-9e02-cd5a86bbe200)

**Comment by katiesavage** [comment]
Can you share the result you get when you type dotnet --info on a terminal?

**Comment by NightcoreRagod** [comment]
> dotnet --info

![Screenshot 2024-09-18 140636](https://github.com/user-attachments/assets/7c978ee9-6f31-4133-9fbd-4189a81d97bb)

**Comment by NightcoreRagod** [comment]
this is what I get..... with respect to the above img
