### ISSUE TITLE
Problema al trabajar .NET con VS Code

### ISSUE THREAD

**Issue by melizaguirre** [dotnet/website-feedback#226]
### URL

https://dotnet.microsoft.com/es-es/learn/dotnet/hello-world-tutorial/create

### Operating system

macos

### Description

cuando busco y selecciono .NET: nuevo proyecto para crear un nuevo proyecto de .NET.
me lanza este error:
El comando ".NET: New Project..." ha dado lugar a un error
Stream terminated before required bytes were read.

### dotnet --info

cuando busco y selecciono .NET: nuevo proyecto para crear un nuevo proyecto de .NET.
me lanza este error:
El comando ".NET: New Project..." ha dado lugar a un error
Stream terminated before required bytes were read.

**Comment by katiesavage** [comment]
*Estoy usando Bing para traducir este mensaje. Disculpas si hay errores.*
¿Qué versión de la CDK tiene instalada? 
¿Puede consultar estas [preguntas frecuentes](https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_why-isnt-c-dev-kit-activating-c-dev-kit-commands-are-not-found) y verificar si no se encuentra con uno de los problemas mencionados?
