### ISSUE TITLE
New Project in Command Palette Cannot Find

### ISSUE THREAD

**Issue by Aangy-sudo** [dotnet/website-feedback#232]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

macos

### Description

<img width="649" alt="Screenshot 2024-09-07 at 9 45 26 PM" src="https://github.com/user-attachments/assets/b6656a7f-796a-4458-bfe8-12a97b3d0147">

I could not find the command palette. I followed the instructions.

**Comment by mairaw** [comment]
and did you install the C# dev kit extension as explained in https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install?
