### ISSUE TITLE
Can't run after create project

### ISSUE THREAD

**Issue by alfikr** [dotnet/website-feedback#234]
### URL

https://dotnet.microsoft.com/id-id/learn/aspnet/blazor-tutorial/run

### Operating system

linux

### More information about your system

~/BlazorApp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

### Description

got error after create project 

~/BlazorApp$ dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  BlazorApp -> /home/danang/BlazorApp/bin/Debug/net8.0/BlazorApp.dll
dotnet watch 🚀 Started

dotnet watch ❌ Exited with error code 139
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

### dotnet --info

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/250/sdk/8.0.400/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.400 [/snap/dotnet-sdk/250/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/snap/dotnet-sdk/250/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/snap/dotnet-sdk/250/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by leecow** [comment]
Canonical is in the process of updating the Snap experience, which may include enhancements to support dotnet watch. Adding @mateusrodrigues to comment.

**Comment by mateusrodrigues** [comment]
Hi @alfikr, that's correct, as it currently stands, the .NET directory hive in the .NET SDK snap sits in an immutable file system, which causes problems for things such as workload installation and some .NET tools. We are working on fixing that.

In the meantime, since you're using Ubuntu 22.04, can I suggest you install our .NET deb package instead?

```
$ sudo snap remove dotnet-sdk
$ sudo apt install dotnet8
```
(you might need to relaunch your terminal window at this point for the alias change to take effect)

Then try running `dotnet watch` on your project again.
