### ISSUE TITLE
InvalidCastException on IncrementAmount 

### ISSUE THREAD

**Issue by scottspencer003** [dotnet/website-feedback#236]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/modify

### Operating system

macos

### Description

I modified the Counter code to add the IncrementAmount parameter but when I pass any amount to it from the Home page using <Counter IncrementAmount="10" /> I get an error that I cant cast a string to Int32. I copy/pasted the code and it still doesnt work. 

### dotnet --info

InvalidOperationException: Unable to set property 'IncrementAmount' on object of type 'BlazorApp.Components.Pages.Counter'. The error was: Unable to cast object of type 'System.String' to type 'System.Int32'.

**Comment by mairaw** [comment]
Can you paste the contents of your Counter.razor page here? 

@danroth27 any other suggestions?

**Comment by scottspencer003** [comment]
@page "/counter"
@rendermode InteractiveServer

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    [Parameter]
    public int IncrementAmount { get; set; } = 1;

    private void IncrementCount()
    {
        currentCount += IncrementAmount;
    }
}

**Comment by scottspencer003** [comment]
And here is the Home page code 

@page "/"

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<Counter IncrementAmount="10" />

**Comment by scottspencer003** [comment]
I have dotnet 8.0.201 installed on an m1 mac.

I am passing an int to IncrementAmount as the tutorial shows <Counter IncrementAmount="10" />
I tried as <Counter IncrementAmount=10 /> as well but that also didn't work.

**Comment by scottspencer003** [comment]
I just got this working by changing the 
@page "/counter" to @page "/counter/{IncrementAmount:int}"

This was not in the tutorial so maybe something changed in dotnet?

**Comment by mairaw** [comment]
I'll make sure to review it.

**Comment by danroth27** [comment]
> I just got this working by changing the @page "/counter" to @page "/counter/{IncrementAmount:int}"
> 
> This was not in the tutorial so maybe something changed in dotnet?

Hi @scottspencer003. Adding that route parameter shouldn't be necessary. You should be able to pass the parameter value directly using an attribute. Can you share with us your original project that reproduces the issue? What does your Home.razor look like?
