### ISSUE TITLE
le sdk ne fonctionne pas

### ISSUE THREAD

**Issue by sop122** [dotnet/website-feedback#239]
### URL

https://dotnet.microsoft.com/fr-fr/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

x64

### Description

le sdk ne fonctionne pas

**Comment by sop122** [comment]
le sdk ne fonctionne pas

**Comment by katiesavage** [comment]
I need some more information. Did you download the SDK and VS Code using the links in [step 1 and 2](https://dotnet.microsoft.com/fr-fr/learn/dotnet/hello-world-tutorial/install)? What error message do you see?
