### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by letticiasabino** [dotnet/website-feedback#241]
### URL

https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

Win11
x64

### Description

PS C:\Projetos\Vídeos\ExemploFundamentos> dotnet new console
dotnet: The term 'dotnet' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### dotnet --info

PS C:\Users\Lettícia> dotnet --info
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

Cargas de trabalho do .NET instaladas:
Configurado para usar loose manifests ao instalar novos manifestos.
Não há cargas de trabalho instaladas para exibir.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Oi @letticiasabino! Você abriu uma nova janela de pois de instalar o SDK para rodar o comando `dotnet new console`? Porque depois você conseguiu executar o `dotnet --info`.

**Comment by letticiasabino** [comment]
Olá @mairaw !

Já consegui resolver. Agradeço o retorno.

**Comment by mairaw** [comment]
Que bom!
