### ISSUE TITLE
Nao sei como resolver o erro que esta dando

### ISSUE THREAD

**Issue by didireis** [dotnet/website-feedback#242]
### URL

https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

win 10

### Description

Não consigo resolver o problema seguinte:
No installed .NET SDK was found on the computer. If it is installed, make sure it can be found through the PATH environment variable. C# Dev Kit does not work without a supported version of SDK. After installing the SDK, you need restart the VS Code session, or the computer.

### dotnet --info

Host:
  Version:      8.0.6
  Architecture: x86
  Commit:       3b8b000a0e
  RID:          win-x86

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
@didireis sinto muito que você esteja tendo problemas. Você pode confirmar se teu Windows é x64?

Pela informação mostrada pelo `dotnet --info`, você tem duas versões instaladas. Se sua máquina for x64, grandes chances de ser um problema com o PATH. 

Rode o comando `where.exe dotnet` e se x86 retornar primeiro e sua máquina for x64, siga as instruções seguintes para tentar arrumar o problema
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

**Comment by didireis** [comment]
sim é x64

**Comment by didireis** [comment]
![image](https://github.com/user-attachments/assets/79b6e965-a795-40d2-bc75-5bb700235f27)

**Comment by mairaw** [comment]
Então é isso. Você vai ter que editar suas variáveis de ambiente para fazer com que o x86 retorne em segundo quando vc executar esse comando.
https://github.com/dotnet/core/issues/5962#issuecomment-780084535

Me avisa se tiver mais dúvidas já que as intruções no outro issue estão em inglês.

**Comment by didireis** [comment]
eu segui os passos la:
![image](https://github.com/user-attachments/assets/7b1c5a95-7cbf-47ff-bf74-14eca55dc0c4)
Depois fui tentar criar um projeto:
![image](https://github.com/user-attachments/assets/f2c80c0f-928b-478d-9df6-ff2fa9790f6f)
Apareceu esse erro agora

**Comment by didireis** [comment]
Tem alguma coisa que possa ser feita?

**Comment by mairaw** [comment]
Você moveu o x86 para baixo? Como no meu exemplo C:\program files\dotnet tem que vir primeiro.

![image](https://github.com/user-attachments/assets/c3fcb175-b6e7-4c41-b2ab-8263a7f40f9c)

**Comment by mairaw** [comment]
Se você fez as mudanças executa `dotnet --info` para confirmar que o SDK agora está aparecendo

**Comment by didireis** [comment]
Como no seu exemplo:
![image](https://github.com/user-attachments/assets/a094a230-255f-4732-afcb-1c7598339f63)
E agora o --info:
dotnet --info
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

Cargas de trabalho do .NET instaladas:
Configurado para usar loose manifests ao instalar novos manifestos.
Não há cargas de trabalho instaladas para exibir.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Perfeito, agora o dotnet --info parece correto. E você reiniciou o Visual Studio Code e continua tendo aquele erro quando você tenta executar o comando?

**Comment by didireis** [comment]
Funcionou, muito obrigado!

**Comment by mairaw** [comment]
Ah que bom! Vou fechar o issue então. Avisa se precisar de mais alguma coisa.
