### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by Sabirhabib** [dotnet/website-feedback#243]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included,     
verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

### dotnet --info

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included,     
verify that the path is correct and try again.
At line:1 char:1
+ dotnet
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by mairaw** [comment]
Sorry to hear you're running into issues. Have you installed the .NET 8 SDK? Have you tried restarting VS Code?

Can you see if you can run the `dotnet --info` command on command prompt or powershell outside of VS Code?
