### ISSUE TITLE
cannot safely run in https (red and crossed)

### ISSUE THREAD

**Issue by hunmundin** [dotnet/website-feedback#244]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### Description

notifications popped out saying do I trust and am I willing to download a specific certificate. I accept all, but upon running, the program cannot run in https safely. https in the URL is red and crossed. How to fix this? Thank you!

**Comment by mairaw** [comment]
Are you getting the NET::ERR_CERT_INVALID error? If so, there are some instructions on the page on how to fix this.
