### ISSUE TITLE
visual studio

### ISSUE THREAD

**Issue by 202305042** [dotnet/website-feedback#245]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### Description

Your connection isn't private
Attackers might be trying to steal your information from localhost (for example, passwords, messages, or credit cards). [Learn more about this warning](chrome-error://chromewebdata/#)
net::ERR_CERT_INVALID

**Comment by mairaw** [comment]
Have you tried following the instructions from the bottom of this page that talks about this specific error?
