### ISSUE TITLE
Privacy Error

### ISSUE THREAD

**Issue by Rinku03062001** [dotnet/website-feedback#250]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### Description

After run the program, it shows that the connection is not private. Attackers might steal your private information.

### dotnet --info

![image](https://github.com/user-attachments/assets/9b2d4135-c83d-4fb2-8296-bab57081e8b4)

**Comment by katiesavage** [comment]
There is some troubleshooting guidance in the "Got an issue?" section at the [bottom of the page](https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run). Could you try to restart all browser windows so the new certificate can be picked up by the browser and run the application again?
