### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by xisuo-clown** [dotnet/website-feedback#251]
### URL

https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### Description

Create your app
1.Open the command palette in VS Code by pressing CTRL+SHIFT+P.
2.Type .NET: to see the commands you can run with C# Dev Kit!
3.Find and select .NET: New Project to create a new .NET project.
4.Scroll down and select Console App.
5.Choose the folder location you'd like to save your project.
6.Name the project MyConsoleApp in the command palette when prompted.
After pressing CTRL+SHIFT+P, didn't see commands related to .NET

**Comment by katiesavage** [comment]
I need some more information. Were you able to see .NET commands when you did step 2 above?

When you enter `dotnet --info` into your terminal, what does it return?
