### ISSUE TITLE
Error installing install-csharp-dev-ket

### ISSUE THREAD

**Issue by darcydommer** [dotnet/website-feedback#253]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### More information about your system

windows 10 home
x86

### Description

Apply :: WinGetPackage [install-dotnet8-SDK]
  Install .NET 8 SDK
  Module: Microsoft.WinGet.DSC by Microsoft Corporation [PSGallery]
    PowerShell Module with DSC resources related to WinGet configurations
  Settings:
    id: Microsoft.DotNet.SDK.8
    source: winget
Apply :: WinGetPackage [install-vs-code]
  Install Visual Studio Code
  Module: Microsoft.WinGet.DSC by Microsoft Corporation [PSGallery]
    PowerShell Module with DSC resources related to WinGet configurations
  Settings:
    id: Microsoft.VisualStudioCode
    source: winget
Apply :: VSCodeExtension [install-csharp-dev-kit]
  Install C# Dev Kit
  Module: Microsoft.VSCode.Dsc by Microsoft Corporation [PSGallery]
    DSC Resource for Visual Studio Code
  Dependencies: install-vs-code
  Settings:
    name: ms-dotnettools.csdevkit
    exist: true
You are responsible for understanding the configuration settings you are choosing to execute. Microsoft is not responsible for the configuration file you have authored or imported. This configuration may change settings in Windows, install software, change software settings (including security settings), and accept user agreements to third-party packages and services on your behalf.  By running this configuration file, you acknowledge that you understand and agree to these resources and settings. Any applications installed are licensed to you by their owners. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages or services.
Have you reviewed the configuration and would you like to proceed applying it to the system?
[Y] Yes  [N] No: y
Apply :: WinGetPackage [install-dotnet8-SDK]
  Configuration successfully applied.
Apply :: WinGetPackage [install-vs-code]
  Configuration successfully applied.
**Apply :: VSCodeExtension [install-csharp-dev-kit]
  Loading the module for the configuration unit failed.
Some of the configuration was not applied successfully.**

Press Enter to continue . . .

### dotnet --info

Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Darcy>dotnet --info
.NET SDK:
 Version:           8.0.206
 Commit:            bb12410699
 Workload version:  8.0.200-manifests.f6879a9a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.206\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by claudiaregio** [comment]
Hi @darcydommer, could you please run `winget -v` in your terminal and share which version of winget you are using?

**Comment by darcydommer** [comment]
Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Darcy> winget -v
v1.8.1911

C:\Users\Darcy>

**Comment by claudiaregio** [comment]
@darcydommer We need the winget team to take a look at this so I've asked a few more questions here (https://github.com/microsoft/winget-dsc/issues/61). If you could go there and provide the information requested we can try and get this debugged! Thank you for your help in improving the install experience!

**Comment by claudiaregio** [comment]
@darcydommer Marking as closed as the issue you were running into was fixed with the latest update of the DSC module.
