### ISSUE TITLE
Can't create AKS cluster due to quota issue?

### ISSUE THREAD

**Issue by djwashburn** [dotnet/website-feedback#255]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/deploy-microservice-tutorial/azure-resources

I'm trying to complete the final step, "Create an AKS cluster", but when I execute the command I get the following error: 

    (ErrCode_InsufficientVCPUQuota) Insufficient regional vcpu quota left for location eastus2. left regional vcpu quota 0, requested quota 825451438968
    Code: ErrCode_InsufficientVCPUQuota
    Message: Insufficient regional vcpu quota left for location eastus2. left regional vcpu quota 0, requested quota 825451438968

I am using the default free plan. Is it possible to complete the tutorial using this plan? What do I do to fix this issue?

### Operating system

windows

### Description

```
(ErrCode_InsufficientVCPUQuota) Insufficient regional vcpu quota left for location eastus2. left regional vcpu quota 0, requested quota 825451438968
Code: ErrCode_InsufficientVCPUQuota
Message: Insufficient regional vcpu quota left for location eastus2. left regional vcpu quota 0, requested quota 825451438968
```

### dotnet --info

.NET SDK:
 Version:           8.0.402
 Commit:            70aa751718
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.402\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
Sorry to hear you're running into this issue. I've found some suggested troubleshooting steps in this [Microsoft Learn forum](https://learn.microsoft.com/en-us/answers/questions/2043637/unable-to-create-aks-resource-why) that may apply to your scenario. Could you try this?

Adding @baronfel in case he has other ideas.
