### ISSUE TITLE
Could not install .NET SDK on my MacOS

### ISSUE THREAD

**Issue by Nanuchaa** [dotnet/website-feedback#260]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install

### Operating system

macos

### Description

Does not react on click on "Download .NET 8 SDK x64 (Intel)" link.

**Comment by katiesavage** [comment]
As an alternative, you can try downloading the SDK from here: https://dotnet.microsoft.com/download

Let me know if this works.

@mairaw this may be a bug.

**Comment by mairaw** [comment]
This is the first time I'm seeing a report of such an issue. Maybe a screen recording or a screenshot would help us to understand a little better what's going on. If your system is x64, then the link that would be pointing to is https://download.visualstudio.microsoft.com/download/pr/d6b3fe61-3c0e-45da-9e37-cef64d4fd3eb/28d536e0ecfbb330ab49454a5e3962f6/dotnet-sdk-8.0.403-osx-x64.pkg currently.
