### ISSUE TITLE
.NET Desktop Runtime 8.1.0 returns a 0 byte file

### ISSUE THREAD

**Issue by HansHartmann** [dotnet/website-feedback#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### URL

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.10-windows-x64-installer

### Browser

Firefox 131.0

### Description

Download link returns a 0 byte file. A friedn told me he doesn't get a valid .exe, so I tried and got the same.

**Comment by mairaw** [comment]
Are you using Firefox by any chance? I've seen some reports of users having issue with that browser.

**Comment by HansHartmann** [comment]
yes, I’m using Firefox. As does the friend who asked me to check. I know that some of the MS websites (partner, supplierweb etc.) have issues with Firefox but I’ve never had any problems with downloading a .NET runtime before.

 

 

Von: Maira Wenzel ***@***.***> 
Gesendet: Dienstag, 8. Oktober 2024 22:42
An: dotnet/website-feedback ***@***.***>
Cc: H. Hartmann ***@***.***>; Author ***@***.***>
Betreff: Re: [dotnet/website-feedback] .NET Desktop Runtime 8.1.0 returns a 0 byte file (Issue #261)

 

Are you using Firefox by any chance? I've seen some reports of users having issue with that browser.

**Comment by mairaw** [comment]
Totally. It's the first release I'm seeing this feedback. Other folks told me that restarting firefox or using a different browser fixed the issue. Can you try that?

**Comment by HansHartmann** [comment]
Yes, I just tried again and this time it downloaded a 57 MB file. It’s strange though that the same issue happens on the same day for one guy in Germany and one in the Netherlands (with a brand new PC).

 

Von: Maira Wenzel ***@***.***> 
Gesendet: Donnerstag, 10. Oktober 2024 01:38
An: dotnet/website-feedback ***@***.***>
Cc: H. Hartmann ***@***.***>; Author ***@***.***>
Betreff: Re: [dotnet/website-feedback] .NET Desktop Runtime 8.1.0 returns a 0 byte file (Issue #261)

 

Totally. It's the first release I'm seeing this feedback. Other folks told me that restarting firefox or using a different browser fixed the issue. Can you try that?

**Comment by GoombaProgrammer** [comment]
same issue for 6.0 on Windows 11, Microsoft Edge
