### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by seyfy** [dotnet/website-feedback#263]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create 

### Operating system

windows

### Description

scriptcs : The term 'scriptcs' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ scriptcs "c:\Users\Seyfullah YALÇIN\Desktop\denemeee\ConsoleApp1\Prog ...
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scriptcs:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException 
 How can i solve it?

**Comment by mairaw** [comment]
We're not using scriptcs as part of the tutorial. Are you following a different article online?

**Comment by seyfy** [comment]
I am using Vs code and I get this error in the terminal

**Comment by mairaw** [comment]
When does this error happen? In which part of the instructions at https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create, does this error appear?

**Comment by seyfy** [comment]
When trying to run the script

**Comment by mairaw** [comment]
But our tutorial doesn't have that script, so that's what I'm trying to understand. which instructions are you trying to follow?
You don't need scriptcs to run our tutorial. If you are following a different tutorial from another site, then we can't really help you.

**Comment by seyfy** [comment]
Yes I am following someone else and I think the problem is with my computer
thank you very much for your help.

**Comment by mairaw** [comment]
If you installed the tools they asked you to install, you can try restarting VS Code or your machine, to see if it recognizes that. 

I'm sorry I can't further help you.
