### ISSUE TITLE
style not found

### ISSUE THREAD

**Issue by TwitchySquid916** [dotnet/website-feedback#27]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

![Screenshot 2024-01-25 163349](https://github.com/dotnet/core/assets/83473982/70346112-5004-46b2-98df-25294c6337c5)
![Screenshot 2024-01-25 163607](https://github.com/dotnet/core/assets/83473982/78cc6938-1a67-49e5-b6d1-231991c16d10)

**Comment by mairaw** [comment]
Can you share your project with us that reproduces the issue? Please include the bin and obj folders.

Would it also be possible for you to collect a binlog when building the problematic project? Instructions for collecting a binlog are here: https://learn.microsoft.com/visualstudio/ide/msbuild-logs?view=vs-2022#provide-msbuild-binary-logs-for-investigation.

/cc @danroth27

**Comment by danroth27** [comment]
@TwitchySquid916 Can you also check if the project runs cleanly from the command-line using `dotnet run`?
