### ISSUE TITLE
it wont let me im hacked

### ISSUE THREAD

**Issue by Chadj7675** [dotnet/website-feedback#275]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/install

### Operating system

windows

### More information about your system

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/noble/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/noble-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/noble-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/noble-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.

### Description

Download .NET 8 SDK (64-bit) 

### dotnet --info

ive been hacked through the url and have rootki, tojan and viruses

**Comment by mairaw** [comment]
I don't understand this issue. Hacked through which URL?

**Comment by Chadj7675** [comment]
Sir we got hacked from a dongle that was like a bad USB. Please by all
means look it up and you'll see what I'm talking about. Once plugged in it
allowed him to get access to every computer in the house with out anyone
knowing. Next thing was with his access he also would show up to work on
these computers because the man in question was the trusted installer. So
at some point he not only had the Trojan presetting all the rules of how
the computer would give him remote access but he sent what's know as a url
hook that came with a nasty virus called the explorer and chrome virus
which hook the url. Also he put a root kit on the computer. You see the
computers he was actually bitmining on and stealing content from Mandy
mayhem material from her music and web sites. When I showed up and started
to peal back the problems he tried to destroy everything in the house using
the trojans, viruses, rootkit and corrupt dns. It was not easy to save
anything at all honestly. But I managed to only lose too computers and
locate and report some of the problems to the FBI and police. I am hoping
you can possibly help me report this so they can help me with this project
and save this person from any more trauma to her life. Thank you very much
for you're time and please any help or advice you can give me I'd be
greatful

**Comment by Chadj7675** [comment]
I also have 5000 photos and documents and I'm having trouble finding a good
way to remove the rootkit and fix the url. My apologies for the long winded
answers but I wanted to show the magnitude of the actual problem site.
Thank you

**Comment by Chadj7675** [comment]
Sorry

**Comment by mairaw** [comment]
I'm sorry but this has nothing to do with the dot.net website. Closing.

**Comment by Chadj7675** [comment]
I got hacked through chrome and explore. Also I have a bad DNS I can't
change. Cox wifi some one has made a fake DNS and when you look it up for
the most part it looks legit entill you think about why would cox wifi in
Las Vegas be running three DNS . Also when I do cmd I end up with a massive
amount of established lines when I type in netstat -nao
