### ISSUE TITLE
Not able to find the styles.css

### ISSUE THREAD

**Issue by JTTELCOR** [dotnet/website-feedback#28]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Looks like we are not able to find the styles.css
Windows 10 Enterprise, Microsoft Visual Studio Enterprise 2022 
![image](https://github.com/dotnet/website-feedback/assets/154908323/9dbb4570-8b9e-44f4-94d8-44252b0da773)

**Comment by JTTELCOR** [comment]
Looks like this might be an issue when having a space in the project name.

**Comment by JTTELCOR** [comment]
Created a new project with no spaces in the project name and it worked as expected.

**Comment by mairaw** [comment]
Thanks for letting us know. We're trying to understand why folks are running into this issue and you might have given us a clue. 

?cc @danroth27
