### ISSUE TITLE
Hero image is 4.2MB and therefore makes first load slow

### ISSUE THREAD

**Issue by warappa** [dotnet/website-feedback#291]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### URL

https://dotnet.microsoft.com/en-us/

### Browser

Edge 130.0.2849.80 

### Description

The [new hero image](https://dotnet.microsoft.com/blob-assets/images/illustrations/hero/netconf2024-hero.png) is **4.2MB** and takes **~2.5 seconds** on a good connection to download it from the server.

![Image](https://github.com/user-attachments/assets/6086449a-04e0-4c5c-807f-91b0b11df07a)

This gives no good first impression for .NET.

This should be much smaller.

**Comment by warappa** [comment]
I just checked again and the image is now replaced.

But I took a look at the .NET Conf page, and there is a svg that is **even bigger: 5.6MB!**

![Image](https://github.com/user-attachments/assets/a8f85e16-7afa-4cc1-9bb4-d8cfe7e04a62)

**Comment by warappa** [comment]
@mairaw Yes, I already discovered this as of my last comment.

Did you read my last comment about https://dotnetconf.com/? Or is this repo not the right place to report issues with https://dotnetconf.com/ also? Because there, the issue that I additionally mentioned persists.

**Comment by mairaw** [comment]
I failed to see the dotnetconf comment. It's not this repo but I'm not sure if they have a public location for feedback. I'll keep this issue open and I'll contact the team directly.

**Comment by mokenk** [comment]
Here is a more optimized image under 1mb. I hope this helps. ![Image](https://github.com/user-attachments/assets/46127215-075b-47b1-91d5-3a4cd12e6f18)

**Comment by mairaw** [comment]
Thank you for reporting the issue. The image size on dotnetconf.net has been reduced.
