### ISSUE TITLE
Content problem: .NET 9 supports F# 9

### ISSUE THREAD

**Issue by goswinr** [dotnet/website-feedback#293]
.NET 9 supports F# 9:
as confirmed here: https://github.com/dotnet/core/blob/main/release-notes/9.0/9.0.0/fsharp.md
but it's shown wrong: 
![Image](https://github.com/user-attachments/assets/5f02dfe7-0541-4708-a106-09e645e04f2f)
https://dotnet.microsoft.com/en-us/download/dotnet/9.0

**Comment by mairaw** [comment]
Sorry for the delay. It's been a busy week with the release and the conference. 

I have opened a PR to fix this at https://github.com/dotnet/core/pull/9612
