### ISSUE TITLE
Failed to get detailed information

### ISSUE THREAD

**Issue by bryanHcollateta** [dotnet/website-feedback#299]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### Operating system

windows

### Description

Failed to get detailed information about the configuration.
Apply :: WinGetPackage [install-dotnet8-SDK]
  Install .NET 8 SDK
  Module: Microsoft.WinGet.DSC
  Settings:
    id: Microsoft.DotNet.SDK.8
    source: winget
Apply :: WinGetPackage [install-vs-code]
  Install Visual Studio Code
  Module: Microsoft.WinGet.DSC
  Settings:
    id: Microsoft.VisualStudioCode
    source: winget
Apply :: VSCodeExtension [install-csharp-dev-kit]
  Install C# Dev Kit
  Module: Microsoft.VSCode.DSC
  Dependencies: install-vs-code
  Settings:
    name: ms-dotnettools.csdevkit
    exist: true
You are responsible for understanding the configuration settings you are choosing to execute. Microsoft is not responsible for the configuration file you have authored or imported. This configuration may change settings in Windows, install software, change software settings (including security settings), and accept user agreements to third-party packages and services on your behalf.  By running this configuration file, you acknowledge that you understand and agree to these resources and settings. Any applications installed are licensed to you by their owners. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages or services.
Have you reviewed the configuration and would you like to proceed applying it to the system?
[Y] Yes  [N] No:

**Comment by katiesavage** [comment]
Could you clarify the issue? Did you press 'Y' after this step?

**Comment by denelon** [comment]
Can you share the output of `winget --info`? I think I've seen this error before, but I don't remember how I encountered it. Having the information about the version of WinGet might help isolate what the problem is.
