### ISSUE TITLE
I am receiving this error while running the command "https://aka.ms/dotnet/app-launch-failed"

### ISSUE THREAD

**Issue by rahim-cmd** [dotnet/website-feedback#30]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when I was executing this command docker run -it --rm -p 3000:8080 --name mymicroservicecontainer mymicroservice It shows me error https://aka.ms/dotnet/app-launch-failed and suggest me to download this things "To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=linux-x64&os=debian.12"

**Comment by mairaw** [comment]
@baronfel do you have any suggestions here?

interesting that it's looking for .NET 7, when the Dockerfile is configured for .NET 8.
Did you make any changes to the proposed sequence on the tutorial @rahim-cmd?

**Comment by baronfel** [comment]
To me that's a pretty clear signal that the app is being targeted at net7.0, but we'd need more details to confirm.

**Comment by mairaw** [comment]
@rahim-cmd can you share what `dotnet --info` returns and what do you in your csproj file?

The tutorial wouldn't work if there's a version mismatch.
