### ISSUE TITLE
the code is not running as expected

### ISSUE THREAD

**Issue by mwangiianjk** [dotnet/website-feedback#300]
### URL

![Image](https://github.com/user-attachments/assets/cabbdf1c-5de0-43b2-9a03-6bc45737578e)

### Operating system

windows 11

### Description

![Image](https://github.com/user-attachments/assets/f76cd85d-eef2-4065-89a0-cdcb99a85822)
am trying to run the code but i keep getting undesired output. have i done anything wrong, if yes what can i change?

**Comment by katiesavage** [comment]
Which tutorial are you currently using? Did you download and install the .NET SDK? Did you install the C# Dev Kit extension into VS Code?
