### ISSUE TITLE
Blazor Unable to access file because it is already being used.

### ISSUE THREAD

**Issue by tom-does-code** [dotnet/website-feedback#301]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add

### Operating system

windows

### More information about your system

Windows 10

### Description

Hello, I'm following this tutorial and have just used the C# Default Blazor package to run & debug. When the page loads there is no styling and I am getting the error "Blazor%20App%20Web%2024.styles.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)". I ignored this error and continued but am now getting this error everytime I try run my app: Could not copy "c:\Users\Halcy\Desktop\Github\Blazor App Web 24\Blazor App Web 24\obj\Debug\net9.0\apphost.exe" to "bin\Debug\net9.0\Blazor_App_Web_24.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'c:\Users\Halcy\Desktop\Github\Blazor App Web 24\Blazor App Web 24\bin\Debug\net9.0\Blazor_App_Web_24.exe' because it is being used by another process. The file is locked by: "Blazor_App_Web_24 (18812)" [c:\Users\Halcy\Desktop\Github\Blazor App Web 24\Blazor App Web 24\Blazor App Web 24.csproj] C:\Program Files\dotnet\sdk\9.0.100\Microsoft.Common.CurrentVersion.targets(5322,5): warning MSB3026:

I have searched up a lot about it and it seems to be something about the previous process not closing properly. I have tried changing the port, ending the VS code process, restarting my pc and rebuilding it but nothing has worked. 

When I press the option to run at last successful build it fails at App.Run(), throwing the error "A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Users\Halcy\Desktop\Github\Blazor App Web 24\Blazor App Web 24\bin\Debug\net9.0\Blazor_App_Web_24.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Users\Halcy\Desktop\Github\Blazor App Web 24\Blazor App Web 24\bin\Debug\net9.0\Blazor_App_Web_24.runtimeconfig.json' file and specify the appropriate framework.
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core."

I apologise for how many errors there are. I am a complete beginner and have never used Blazor.

Thank you

### dotnet --info

.NET SDK:
 Version:           9.0.100   
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maui\9.0.0\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    18.0.9617/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.maccatalyst\18.0.9617\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    18.0.9617/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.ios\18.0.9617\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    35.0.7/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.sdk.android\35.0.7\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  8.0.402 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by katiesavage** [comment]
Are you using the C# Dev Kit extension in VS Code to complete the tutorial?

@danroth27 have you seen this issue before? Can you advise?

**Comment by danroth27** [comment]
@katiesavage Nope, I haven't seen this one before.

@tom-does-code How did you run the app the previous time you ran it? Did you run it from the command-line, maybe using `dotnet run` or `dotnet watch`? Or did you run it from Visual Studio, perhaps with the debugging?

**Comment by tom-does-code** [comment]
@danroth27 

Hi, the previous time I used visual studio code debugging. 

Just after seeing your message I decided to just start a new project and it seems to be working just fine. Thank you @danroth27 and @katiesavage

**Comment by danroth27** [comment]
@tom-does-code Cool, I'm glad you were able to get yourself unblocked.

@webreidi FYI - it sounds like there was potentially an issue here with VS Code to shutting down the .NET process cleanly after debugging.
