### ISSUE TITLE
Create .net console project from vs code

### ISSUE THREAD

**Issue by DharmPatel4300** [dotnet/website-feedback#302]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
![Image](https://github.com/user-attachments/assets/59434d3e-a26b-4e2c-b3f6-e05b2ff8cfff)

I am not getting option to create new project.

### Operating system

windows

### More information about your system

windows 10

### Description

I followed tutorial step but not able to get option to create new project

### dotnet --info

PS C:\Users\Parth Computer> dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.       
  --list-sdks       Display the installed SDKs.     
  --list-runtimes   Display the installed runtimes.

**Comment by claudiaregio** [comment]
Hi @DharmPatel4300, are you able to look at your extensions in vs code and share what you have installed? You should have the C# and C# Dev Kit installed in addition to the .NET Install Tool. 

![Image](https://github.com/user-attachments/assets/027412c8-4210-465a-b21b-47ffd61ba91e)
