### ISSUE TITLE
The name 'salesTotalDir' does not exist in the current contextCS0103

### ISSUE THREAD

**Issue by Khunsu** [dotnet/website-feedback#305]
### URL

I followed the instructions according the lessons in Microsoft Learn, but I Kepp getting this error message that the name does not exist in the path. I did not copy & paste this. I followed the instructions. After trying twice, I then copied and pasted. The copy & paste seemed to work but MY actual efforts seemed to fail. Even though the "Got Stuck" section is a direct replica of my manual work efforts, it still fails to work.
  Am I still missing something here? Is This something that happens often?  It's starting to become discouraging.

### Operating system

Window 11

### Description

using System.IO;
using System.Collections.Generic;

var currentDirectory = Directory.GetCurrentDirectory();
var storesDirectory = Path.Combine(currentDirectory, "stores");

var SalesTotalDir = Path.Combine(currentDirectory, "salesTotalDir");
Directory.CreateDirectory(salesTotalDir);
var salesFiles = FindFiles(storesDirectory); 

File.WriteAllText(Path.Combine(salesTotalDir, "totals.txt"), String.Empty);

static IEnumerable<string> FindFiles(string folderName)
{
    List<string> salesFiles = [];

    var foundFiles = Directory.EnumerateFiles(folderName, "*", SearchOption.AllDirectories);

    foreach (var file in foundFiles)
    {
        var extention = Path.GetExtension(file);
        if (extention==(".json"))
        {
            salesFiles.Add(file);
        }
    }

    return salesFiles;
**}**

### dotnet --info

.NET SDK:
 Version:           9.0.100-rc.2.24474.11
 Commit:            315e1305db
 Workload version:  9.0.100-manifests.cea95dba
 MSBuild version:   17.12.0-preview-24473-03+fea15fbd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.2.24474.11\   

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    34.99.0-preview.6.340/9.0.100-preview.6    
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.android\34.99.0-preview.6.340\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6  
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maui\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6        
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maccatalyst\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.11.35327.3
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6        
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.ios\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.   

Host:
  Version:      9.0.0-rc.2.24473.5
  Architecture: x64
  Commit:       990ebf52fc

.NET SDKs installed:
  8.0.402 [C:\Program Files\dotnet\sdk]
  8.0.403 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.2.24474.11 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.2.24474.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.2.24473.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.2.24474.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS D:\WorkingWithDirectories>

**Comment by mairaw** [comment]
Can you clarify which tutorial on learn are you following?

**Comment by Khunsu** [comment]
Apologies for the late response. The Tutorial is: Work with files and directories in a .NET app.
   Now, for some reason, I cannot save and quit this tutorial. Once I returned, I receive the following message: 
    Couldn't find a project to run. Ensure a project exists in D:\Workingwithdirectory, or pass the path to the project using --project.

**Comment by mairaw** [comment]
@Khunsu can you share the url for the tutorial? You're probably just missing a change directory command (cd) to the folder where the csproj is located. 

Is this this one?
https://learn.microsoft.com/en-us/training/modules/dotnet-files/

Can you share the contents of Workingwithdirectory?

**Comment by mairaw** [comment]
Tagging @codemillmatt to help as well.

**Comment by codemillmatt** [comment]
Hi @Khunsu - there's a typo where you initialized the `salesTotalDir` variable. Make sure the first **s** is lower case. The below will work. (cc @mairaw)

```csharp
  var salesTotalDir = Path.Combine(currentDirectory, "salesTotalDir");
  Directory.CreateDirectory(salesTotalDir);
  var salesFiles = FindFiles(storesDirectory);
  
  File.WriteAllText(Path.Combine(salesTotalDir, "totals.txt"), String.Empty);
```

**Comment by Khunsu** [comment]
Ok. Thank you
