### ISSUE TITLE
Explore APIs with Command Line HTTP REPL

### ISSUE THREAD

**Issue by Khunsu** [dotnet/website-feedback#310]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### URL

https://learn.microsoft.com/en-us/training/modules/build-web-api-aspnet-core/3-exercise-create-web-api

### Describe what you'd like to see

As I try to complete the tutorial in Exercise - Create a web API project,
under the section:
Optional: Explore APIs with Command Line HTTP REPL:
Connect to the web API by running the following command:

.NET CLI

Copy
httprepl https://localhost:{PORT}

I am continuously disconnected in my terminal as follow:

PS D:\ContosoPizza> httprepl https://localhost:{5241}

(Disconnected)> connect https://localhost: -encodedCommand NQAyADQAMQA= -inputFormat xml -outputFormat text
UnknownOption -- -encodedCommand
UnknownOption -- -inputFormat
UnknownOption -- -outputFormat
Usage: connect [rootAddress] [--base baseAddress] [--openapi openApiDescriptionAddress] [--verbose] [--persist-headers] [--persist-paths]

Configures the directory structure and base address of the api server based on the arguments and options specified. At least one of [rootAddress], [--base baseAddress] or [--openapi openApiDescriptionAddress] must be specified

By default, existing headers set via the `set header` command and path segments beyond the base address are cleared when this command is executed. Use [--persist-headers] and [--persist-paths] to change those defaults

[rootAddress] will be used to automatically determine the base address and OpenAPI description address
[--base baseAddress] and [--openapi openApiDescriptionAddress] allow you to explicitly set those addresses and skip auto detection
[--verbose] provides more detail about OpenAPI Description discovery and parsing
[--persist-headers] leaves existing session headers in place when connecting to a new API       
[--persist-path] leaves existing path segments in place when connecting to a new API

Am I doing something wrong?

**Comment by Khunsu** [comment]
The following instruction is under the tutorial:
 Optional: Explore APIs with Command Line HTTP REPL
Secton 3: 
  Explore available endpoints by running the following command:

.NET CLI

Copy
ls

**Comment by mairaw** [comment]
@jongalloway you seem to own this Learn module. Can you please check?

**Comment by jongalloway** [comment]
Hi @Khunsu -

Don't include the {} characters in the URL. So in this case, you should be using
```bash
httprepl https://localhost:5241
```

+ @CamSoper who is looking at these modules
