### ISSUE TITLE
Project not recognized

### ISSUE THREAD

**Issue by turnkeytitan** [dotnet/website-feedback#33]
![ojgYtjkFg2](https://github.com/dotnet/core/assets/12472612/72a82765-d39f-4517-8f5b-2f87b875b978)
Problem encountered on https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/create
Operating System: windows

in this page: https://dotnet.microsoft.com/es-es/learn/aspnet/blazor-tutorial/create after hitting the create button it doesn't recognize the project and it says Solution 'BlazorApp1' (0 projects)

**Comment by mairaw** [comment]
Can you share with us what `dotnet --info` returns?
