### ISSUE TITLE
issue scriptsc not found

### ISSUE THREAD

**Issue by yashg091999** [dotnet/website-feedback#34]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

zsh: command not found: scriptcs

**Comment by mairaw** [comment]
Can you please provide more information about this issue?

Does that error show up when you click run?

/cc @claudiaregio @webreidi

**Comment by yjfvictor** [comment]
I also faced this issue.

The result is:
"C# Dev Kit" conflicts with "Code Runner" (Id: `formulahendry.code-runner`).
Disabling "Code Runner" makes it work well.
