### ISSUE TITLE
ms-dotnettools.csdevkit requested to download the .NET Runtime.

### ISSUE THREAD

**Issue by naflanmohamed** [dotnet/website-feedback#36]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

ms-dotnettools.csdevkit requested to download the .NET Runtime.
Downloading .NET version(s) 7.0.16~x64 ......................................................................... Done!

**Comment by mairaw** [comment]
Hmmm, it shouldn't be using .NET 7. Can you share what the command `dotnet --info` returns if you type that on the terminal? Did you download and install the .NET 8 SDK?
