### ISSUE TITLE
Build your first web app with ASP.NET Core using Blazor

### ISSUE THREAD

**Issue by petebennett** [dotnet/website-feedback#38]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

How do I fix this? I am switching from years of VB development to C# - SOS

source: https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

![Screenshot 2024-02-15 154017](https://github.com/dotnet/website-feedback/assets/3850320/6a8a5734-5900-4efe-9ab1-8a826bb21662)

Versions Installed 
![image](https://github.com/dotnet/website-feedback/assets/3850320/d76b5e84-6f7b-4636-a1d9-5b6f45bb84b7)

**Comment by mairaw** [comment]
@petebennett I'm sorry you're running into issues. From the error messages you're showing, it seems you're running VS 2022 17.7. In order to run .NET 8 apps, you need to VS 2022 17.8. Can you upgrade your VS version and try again?

And I'll add to the steps that you need that version as a minimum.

**Comment by petebennett** [comment]
I can upgrade - which tool should I use.  Thanks

**Comment by petebennett** [comment]
Found it! :)

**Comment by mairaw** [comment]
Alright! I was going to say to just open Visual Studio Installer and it should show you the option to Update.

**Comment by petebennett** [comment]
I had already updated it a few months back - I am older now, keeping up presents challenges but VS Installer working right now.  thanks for the quick help!

**Comment by mairaw** [comment]
No worries! Let me know if you can now run the project without issues.
