### ISSUE TITLE
Not able to run the web api project

### ISSUE THREAD

**Issue by djgithu** [dotnet/website-feedback#39]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: windows

Error : Package Microsoft.AspNetCore.OpenApi 8.0.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.OpenApi 8.0.1 supports: net8.0 (.NETCoreApp,Version=v8.0)

I have .net 8.0.101 installed on the machine.

**Comment by mairaw** [comment]
Can you let us know what `dotnet --info` shows? And can you ensure that the project is targeting .NET 8 in the csproj file?

**Comment by djgithu** [comment]
Hello @mairaw 
Thank you for trying to help. I was finally able to resolve the issue by downloading latest .net core runtime. I also had to restart machine before compiling the project.
