### ISSUE TITLE
v2ray

### ISSUE THREAD

**Issue by mahnazpashaei** [dotnet/website-feedback#41]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
What is the issue you're having @mahnazpashaei? We'll need more information to be able to try to help you.

**Comment by mairaw** [comment]
This issue was closed because there was no response to a request for more information for 10 days.
