### ISSUE TITLE
Errors with .Net 8

### ISSUE THREAD

**Issue by jav1er20** [dotnet/website-feedback#42]
I installed donet sdk 8.0.201 and to check if it was installed well I typed "dotnet" in the cmd but when I do the same in the visual studio code finish it does not recognize it. My processor architecture is x64 and I installed the extensions you show in the tutorial. how do I fix it?

**Comment by mairaw** [comment]
Can you show the output of `dotnet --info` from cmd?

Have you previously installed other versions? Maybe there's an issue with PATH.

Check what `where.exe dotnet` returns as well.

**Comment by jav1er20** [comment]
Thanks for your time. I don't know how, but the problem I had was fixed
just by closing and reopening the visual studio code

**Comment by mairaw** [comment]
Thanks for letting us know. Yeah, sometimes it just needs a restart for the changes to be picked up by the tool.
