### ISSUE TITLE
/learn/dotnet/hello-world-tutorial/ fails after first successful run.

### ISSUE THREAD

**Issue by ddlakoduk** [dotnet/website-feedback#43]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Windows 10 Home;
Version: 22H2 
16GB 
256GB SSD

Running VS Code as Administrator using https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit

Program.cs
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

[Window Title]
Visual Studio Code

[Main Instruction]
Build Failures

[Content]
'C:\code\ConsoleAppNET8\ConsoleAppNET8\ConsoleAppNET8.csproj' failed to build. Would you like to continue and run the last successful build?

[Yes] [No]

 *  Executing task: dotnet: build C:\code\ConsoleAppNET8\ConsoleAppNET8\ConsoleAppNET8.csproj 

dotnet build C:\code\ConsoleAppNET8\ConsoleAppNET8\ConsoleAppNET8.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary 
MSBuild version 17.9.4+90725d08d for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : error CS2012: Cannot open 'C:\code\ConsoleAppNET8\ConsoleAppNET8\obj\Debug\net8.0\ConsoleAppNET8.dll' for writing -- 'The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\code\ConsoleAppNET8\ConsoleAppNET8\obj\Debug\net8.0\ConsoleAppNET8.dll'' [C:\code\ConsoleAppNET8\ConsoleAppNET8\ConsoleAppNET8.csproj]

**Comment by mairaw** [comment]
There are many possibilities that could generate this error message.
Have you tried restarting VS Code?
If so, have you tried closing VS Code, deleting the bin folder inside your project (debug/release folder) and starting VS Code again?
Another possibility could be a MSBuild process hung on task manager.

Try a few different things and let us know if this helped.
