### ISSUE TITLE
error creating my first visual basic program

### ISSUE THREAD

**Issue by ammarkamell** [dotnet/website-feedback#44]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image_2024-02-19_164246368](https://github.com/dotnet/website-feedback/assets/160508399/c49479d0-86e9-4568-b37d-192b525e36d1)

**Comment by mairaw** [comment]
Have you installed the .NET 8 SDK as instructed?

If so, can you let us know what the `dotnet --info` command returns?
You can type that in the VS Code terminal

**Comment by mairaw** [comment]
But also, you mentioned Visual Basic program in your issue title. The tutorial is written for C#.
