### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by newpreetam** [dotnet/website-feedback#45]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

Windows 10

![image](https://github.com/dotnet/website-feedback/assets/8438304/6a14fdd6-11e3-43ee-b3e1-731dd85dace3)

![image](https://github.com/dotnet/website-feedback/assets/8438304/03ee6ef0-5bf0-48e1-9eb0-80a0ef441a59)

**Comment by mairaw** [comment]
In that step, the address should be http://localhost:3000/weatherforecast.

Have you tried that?
