### ISSUE TITLE
found markup element with unexpected name 'page title' if this is intended to be component, add a @using directive for its name space

### ISSUE THREAD

**Issue by Arashsibdari** [dotnet/website-feedback#47]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/modify
Operating System: windows

im in very first introduction of blazor app and in home.razor page, it shoots this error while trying to use parameter of counter component in home.razor : "found markup element with unexpected name 'page title' if this is intended to be component, add a @using directive for its name space"
![Capture](https://github.com/dotnet/website-feedback/assets/106091905/99137650-8799-486e-9410-740f3a8c3a90)

**Comment by mairaw** [comment]
Did you manage to run the app on the previous step and you started getting this error on this step only?

/cc @danroth27

**Comment by alan-man** [comment]
Hello @mairaw, I have the same problem shown in this screenshot:
![Screenshot from 2024-07-02 00-08-56](https://github.com/dotnet/website-feedback/assets/60308523/73e328fa-f769-4d9c-89cf-f43a1d672cbb)
It's only a warning and the app runs. It also shows in previous steps.
