### ISSUE TITLE
Blazor Getting Started... SSL Connection could not be established

### ISSUE THREAD

**Issue by sealamb** [dotnet/website-feedback#5]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am using OSX Sonoma - 14.3.1 and I recently performed a clean up of old applications, deleting Visual Studio and old versions of dotnet, leaving only dotnet 8.0.101.
Attempting to create BlazorApp per instructions results in errors... 
prefix: "/usr/local/share/dotnet/sdk/8.0.101/NuGet.targets(156,5): error :"
----Unable to load the service index for source https://api.nuget.org/v3/index.json.
----The SSL connection could not be established, see inner exception.
----Unable to write data to the transport connection: Broken pipe.
----Broken pipe

I performed dev-certs clean and trust several times to refresh the certificates and each time did a check to ensure the certs were cleared and renewed.

I considered refreshing my dotnet 8 installation.  I tried to uninstall dotnet 8 with the uninstaller, but the uninstaller does not support uninstalling dotnet 8 or above

I tried creating a simple console app in the cli to see if this problem was isolated to blazor.  I received the same errors as above.

I wanted to try deleting everything in the /usr/local/share/dotnet directory, but I am concerned that may cause my problem to get worse.

Any suggestions or help will be greatly appreciated.

Thank you

**Comment by mairaw** [comment]
@danroth27 can you help with this one?

**Comment by danroth27** [comment]
It looks like connecting to nuget.org to restore the packages failed. Adding @JonDouglas to help out on the NuGet side. 

@sealamb Are you able to browse to https://api.nuget.org/v3/index.json without issue?

**Comment by sealamb** [comment]
@danroth27 Yes, I am able to open the link in a browser without issue.

After seeing this may be a nuget issue, I attempted  "dotnet netget  trust" with the following results, which are similar to what I had reported before:

$dotnet nuget trust list                                                                                         
There are no trusted signers.
$dotnet nuget trust source NuGetTrust --source-url https://api.nuget.org/v3/index.json --owners "Nuget;Microsoft" -v d
X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.101/trustedroots/codesignctl.pem'.
X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.101/trustedroots/timestampctl.pem'.
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   The SSL connection could not be established, see inner exception.
error:   Unable to write data to the transport connection: Broken pipe.
error:   Broken pipe

**Comment by sealamb** [comment]
SOLVED ...

I had the guts this morning to delete the /usr/local/share/dotnet directory and files.  I installed a new the dotnet sdk from the Blazor Tutorial page and verified thet 8.0.101 was installed.  I attempted to create a blazor app and came up with the same errors as before.  Therefore, I see the problem is with my system not dotnet.  

Suspecting firewall blocking as a first possibility, I turned off McAfee firewall and attempted to build a blazor app again... It Worked!   I am able to build dotnet applications now on this machine.

Thank you for your help and quick response.

**Comment by mairaw** [comment]
@JonDouglas should we move this to the nuget repo?

**Comment by JonDouglas** [comment]
Seems resolved, but yes for future NuGet source problems our repo is a great place.

**Comment by versile2** [comment]
TDLR - in my bash terminal from windows using Rider I ran
 `dotnet nuget trust source NuGetTrust --source-url https://api.nuget.org/v3/index.json --owners "Nuget;Microsoft" -v d ` 
and suddenly my issues are fixed.
