### ISSUE TITLE
Running the app

### ISSUE THREAD

**Issue by glengoda** [dotnet/website-feedback#52]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 

When running the app I get error: The current NET SDK does not support targeting NET 8.0. Either

NETSDK1 target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0.

**Comment by mairaw** [comment]
Can you confirm what version of VS are you running on?

Also, can you open a command prompt or PowerShell window and run `dotnet --info` to see which versions of the .NET SDK you have installed?

**Comment by glengoda** [comment]
I’m using version 17.4.5 and I did find out that it doesn’t support .net 8

**Comment by mairaw** [comment]
Correct @glengoda. Can you update your version of VS and try again?

**Comment by glengoda** [comment]
Yes, it works!

**Comment by mairaw** [comment]
Great to hear @glengoda! Closing the issue then.
