### ISSUE TITLE
Blazor Web App template Not Found !

### ISSUE THREAD

**Issue by aghaamou** [dotnet/website-feedback#53]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Blazor Web App template Not Found
Visual Studio 2022 17.0.4
dotnet version : 9.0.100-preview.1.24101.2

**Comment by mairaw** [comment]
In order to run the tutorial, you must ensure you're running VS 17.8 or later. Can you update your version of VS and see if that resolves the issue for you?

Or you can run the CLI version of the tutorial:
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/intro

**Comment by mairaw** [comment]
No worries! Just let me know if this works or if you're still having issues.
