### ISSUE TITLE
Unable to create new C# project from VS code

### ISSUE THREAD

**Issue by Thao-Dang-Vu-Phuong** [dotnet/website-feedback#6]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
I already installed the SDK sucessfully
![image](https://github.com/dotnet/website-feedback/assets/136581163/fca370a2-afd1-4edf-8f76-3afca47869ed)

But when I try to create new project from VScode, it showed me this error
![image](https://github.com/dotnet/website-feedback/assets/136581163/c06e3d2c-7789-44b0-98ed-1d2d6b97f3cb)

**Comment by mairaw** [comment]
I'm sorry to hear you're running into issues @Thao-Dang-Vu-Phuong.

Can you please provide the information returned by `dotnet --info` to help us troubleshoot? Did you install the .NET SDK already?
