### ISSUE TITLE
An unhandled error has occurred

### ISSUE THREAD

**Issue by shoaibsaikat** [dotnet/website-feedback#61]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Browser: edge, chrome

Home page shows "An unhandled error has occurred. [Reload](https://localhost:7211/) 🗙"
Page does not show any css styling.

**Comment by shoaibsaikat** [comment]
![Screenshot 2024-02-22 214525](https://github.com/dotnet/website-feedback/assets/6869220/88dbc191-87a4-46cb-ae87-f3501592c598)

**Comment by mairaw** [comment]
What is the name you've given to your project? We are currently seeing many reports of this issue for project names that contain spaces.

This is a known issue and they're working on a fix:
https://github.com/dotnet/aspnetcore/issues/52519

Maybe try creating a project with a name without spaces and see if you can run the project without issues.

If that's not the case, let us know so we can ask for more information that will help us investigate the issue.
