### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by yukiyosarlet** [dotnet/website-feedback#62]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

i instal C# Dev Kit, and i say to run a new terminal but at the bottum debug consol and parts i dont have terminal standing
<img width="1086" alt="terminal" src="https://github.com/dotnet/website-feedback/assets/99720697/c62b0648-af7b-43b0-ada2-7351e6df37b0">

**Comment by mairaw** [comment]
Did you open a new terminal as shown in the tutorial?

![image](https://github.com/dotnet/website-feedback/assets/12971179/82c2e925-8ade-4794-9677-23bbc9419749)
