### ISSUE TITLE
ONLY RUN AT ARM64?

### ISSUE THREAD

**Issue by 006richard** [dotnet/website-feedback#63]
Problem encountered on https://dotnet.microsoft.com/zh-cn/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Not, it should run in x86 and x64 too. Is it showing only the arm64 link? Is your machine a different processor?
