### ISSUE TITLE
ERROR: "docker buildx build" requires exactly 1 argument.

### ISSUE THREAD

**Issue by dharminder0** [dotnet/website-feedback#65]
docker build -t mymicroservice giving error ERROR: "docker buildx build" requires exactly 1 argument.

Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-image
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
The command on the tutorial is `docker build -t mymicroservice .`.

Have you tried that one?
