### ISSUE TITLE
The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	BlazorApp2.Client	C:\Users\new\source\repos\BlazorApp2\BlazorApp2\BlazorApp2.Client\Program.cs	1	Active

### ISSUE THREAD

**Issue by nwaapz** [dotnet/website-feedback#67]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

what is wrong with Microsoft?

**Comment by mairaw** [comment]
Are you running the template code as is? What version of Visual Studio and .NET do you have installed?

For .NET, you can type `dotnet --info` on the command prompt.
