### ISSUE TITLE
I ran the command "fsutil file createnew Dockerfile 0" and a Dockerfile was created but it was empty (no contents) 

### ISSUE THREAD

**Issue by splaton2016** [dotnet/website-feedback#68]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/docker-file
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Correct. The next steps on the tutorial go over replacing the empty Dockerfile with actual content. Have you done that?

![image](https://github.com/dotnet/website-feedback/assets/12971179/15cea05e-28c0-4061-9b5a-925762677d52)

**Comment by splaton2016** [comment]
Hello, 
Thank you very much for your time and support.Yes, you can close the issue please.
Thanks,Savvas 
 

    On Friday, 8 March 2024 at 01:24:06 CET, github-actions[bot] ***@***.***> wrote:  
 
 


This issue was closed because there was no response to a request for more information for 10 days.
