### ISSUE TITLE
a solution file (MyMicroservice.sln) was not created 

### ISSUE THREAD

**Issue by splaton2016** [dotnet/website-feedback#69]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
You're right. I'll fix the tutorial.

**Comment by splaton2016** [comment]
Dear Maira, 
Thank you very much for your support.
Kind Regards,Savvas 
 

    On Tuesday, 27 February 2024 at 00:46:15 CET, Maira Wenzel ***@***.***> wrote:  
 
 


You're right. I'll fix the tutorial.
