### ISSUE TITLE
.Net Download

### ISSUE THREAD

**Issue by neverlosemax** [dotnet/website-feedback#73]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Can you give more information about the issue you're having?

Which macos do you have?

**Comment by neverlosemax** [comment]
14.3.1
