### ISSUE TITLE
how to avoid underline in <counter/>

### ISSUE THREAD

**Issue by Sandipo23** [dotnet/website-feedback#74]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/add
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://github.com/dotnet/website-feedback/assets/159416269/8da57779-1caf-4694-951c-00c3fe8e1ec5)
![Screenshot 2024-02-27 105836](https://github.com/dotnet/website-feedback/assets/159416269/0885fcc5-382f-4cf7-a46d-fbb6fc8f17dc)

**Comment by mairaw** [comment]
@danroth27 any suggestions here?

**Comment by danroth27** [comment]
It looks like the Razor editor hit some issue with component discovery. @phil-allen-msft FYI.

@Sandipo23 What version of Visual Studio are you using? Does the project still build and run in spite of the error in the editor?

To get the editor working properly, can you try restarting Visual Studio?
