### ISSUE TITLE
I run into issues when starting the blazor app

### ISSUE THREAD

**Issue by HakimAbdul12** [dotnet/website-feedback#75]
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS9057	The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'.	BlazorApp1	C:\Users\Hakim\OneDrive\Desktop\C#\BlazorApp1\CSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'BlazorApp1' could not be found (are you missing a using directive or an assembly reference?)	BlazorApp1	C:\Users\Hakim\OneDrive\Desktop\C#\BlazorApp1\Program.cs	1	Active

**Comment by mairaw** [comment]
Are you getting those errors in Visual Studio? Can you make sure your VS is up to date?

@danroth27 any other suggestions?

**Comment by danroth27** [comment]
> Warning CS9057 The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators.dll' references version '4.9.0.0' of the compiler, which is newer than the currently running version '4.8.0.0'.

@chsienki @javiercn Any ideas on how a user could get into this state?

**Comment by chsienki** [comment]
@danroth27 This is happening because the latest SDK (8.0.200) isn't supported in older VS's. The razor SG is compiled against a newer Roslyn version than VS is providing.

The resolution is to either upgrade VS or downgrade the SDK version. I'm not sure on the exact VS version needed but @jjonescz should know.

**Comment by danroth27** [comment]
@HakimAbdul12 Are you able to upgrade your Visual Studio version to the latest supported release?

**Comment by jjonescz** [comment]
SDK 8.0.200+ is compatible with VS 17.9
SDK 8.0.100+ is compatible with VS 17.8

For more details / other scenarios, see https://github.com/dotnet/razor/issues/9935.
