### ISSUE TITLE
Starting to learn .NET. Hello World is not output. I am getting an error

### ISSUE THREAD

**Issue by JijiMardi** [dotnet/website-feedback#77]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://github.com/dotnet/website-feedback/assets/161498887/85315d6a-bdaa-4ff7-bf61-336ce76f6b76)
 Says 'C:\users\Nina\New Console Project\MyConsoleApp\bin\Debug\net8.0\MyConsoleApp.exe' does not exist

**Comment by timheuer** [comment]
@JijiMardi can you paste your launch.json file? Looks like perhaps the path there is wrong.  For context, a launch.json definition takes precedent than any other launcher.

**Comment by JijiMardi** [comment]
I deleted the .vscode folder and tried it again but still getting an error:
![image](https://github.com/dotnet/website-feedback/assets/161498887/1c5bb4ba-4354-4544-8587-73089200ba5b)

This is the expanded version of the bin folder
![image](https://github.com/dotnet/website-feedback/assets/161498887/6be07edd-20dc-42eb-9747-bfb11333aa8f)

When I type dotnet run, I get the following message:
![image](https://github.com/dotnet/website-feedback/assets/161498887/f7439aae-56df-4fa4-9fcd-c573b157792c)

Thank you.

**Comment by timheuer** [comment]
Hmm, @JijiMardi it still is trying to use a launch profile. In the 2nd and 3rd updated screenshots i see launch.json appearing again.  This is very strange that VSCode is saying that path isn't there...can you completely delete .vscode folder again?  Is anything prompting you and causing the launch.json to be created?

You should be seeing something like this (ignore the azure functions dialog at the end):

https://github.com/dotnet/website-feedback/assets/4821/c19d90d3-5a3b-479e-a33c-11c4b0beb39e

For the dotnet run message, go into the project directory first. so:
- `cd MyConsoleapp`
- `dotnet run`

I suspect this will work, but we should figure out what is causing launch.json to be created and that error.

**Comment by JijiMardi** [comment]
I deleted the folder and created a new one to start fresh. As soon as I add the project name, it gives this error:
![image](https://github.com/dotnet/website-feedback/assets/161498887/3ca4aeb6-e4f9-4f83-8d8d-2b9d29e17ea5)

When I click on Check Error, this is what I see:
![image](https://github.com/dotnet/website-feedback/assets/161498887/94106f07-903a-4f8a-89eb-3fb23c262676)

I have reinstalled C# Dev Kit couple times already.

When I Run the project, it gives me the error message. When I click on Open 'Launch.json' it seems to create the VSCode. This time I cancelled it and 
![image](https://github.com/dotnet/website-feedback/assets/161498887/2a56fd50-d4a2-4a8e-a710-a7b9bfd408cf)

Going to the project directory and typing dotnet run works:

![image](https://github.com/dotnet/website-feedback/assets/161498887/6cd30133-ed1c-468f-be05-383b5d129a1c)

**Comment by timheuer** [comment]
Ok, thank you for these steps.  After you cancelled the error message if you click that run menu option again is it a 100% consistent fail?

**Comment by JijiMardi** [comment]
Yes. The run menu consistently gives me this error:
![image](https://github.com/dotnet/website-feedback/assets/161498887/f0d114c1-8ec1-49a0-8430-f11c88e43038)

**Comment by timheuer** [comment]
Ugh, thanks (and sorry) @JijiMardi this is definitely not the desired experience. I think it would be most efficient to see if we can work together real-time to see what is going on in your environment. Are you open to a screenshare session? If so, what timezone are you in?

**Comment by timheuer** [comment]
Kamino closed and cloned this issue to [microsoft/vscode-dotnettools](https://github.com/microsoft/vscode-dotnettools/issues/966)

**Comment by timheuer** [comment]
FYI I moved this to the right repo to continue to track so you'll see a link change here...let's continue the convo at https://github.com/microsoft/vscode-dotnettools/issues/966

**Comment by JijiMardi** [comment]
Yes, I am open to screenshare my session. I am in the EST zone.
________________________________
