### ISSUE TITLE
.netのコンソールプロジェクトが作成されない

### ISSUE THREAD

**Issue by ayame0328** [dotnet/website-feedback#78]
VSCodeをインストールした状態で.net core (8.0.2?)をインストールし、C#の拡張機能をインストールした後に新しいプロジェクトを作成したがエラーメッセージが表示され作成されなかった。
![image](https://github.com/dotnet/website-feedback/assets/72743131/ab532f0f-ac58-41f3-b151-3d2afd66de8e)
![スクリーンショット 2024-02-28 174053](https://github.com/dotnet/website-feedback/assets/72743131/369f4166-92db-4227-a2e1-f5320752d2d3)

**Comment by mairaw** [comment]
Can you type `dotnet --info` on the terminal and let me know what it returns?

**Comment by ayame0328** [comment]
返信ありがとうございます。

下記がdotnet --infoの出力になります。

Host:
  Version:      7.0.10
  Architecture: x86
  Commit:       a6dbb800a4

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
You might be running into an issue with PATH. Which processor is your machine - x86 or x64?

Also, see what `where.exe dotnet` returns. If x86 returns first and your machine is x64, follow the instructions at https://github.com/dotnet/core/issues/5962#issuecomment-780084535 to fix the PATH
