### ISSUE TITLE
I cant open any template or find any template in the latest vscode , would be in search to open a blazor template project

### ISSUE THREAD

**Issue by xdFelix** [dotnet/website-feedback#79]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment]
Hi @xdFelix 
Our Windows version of the tutorial is using Visual Studio 2022 and not VS Code.

You could use the CLI version to create the project
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/create

and then open it in VS Code.
