### ISSUE TITLE
CSS not accessible while I run the app

### ISSUE THREAD

**Issue by ErNivasIT** [dotnet/website-feedback#8]
![image](https://github.com/dotnet/website-feedback/assets/75535050/0f98b309-cb28-4328-917d-26a7f6b9aa24)

**Comment by ErNivasIT** [comment]
I learning the Blazor, While I create App and run it, bootstrap is not loading, while it presents in wwwroot / css folder.
Please let me know which issue was there.

Thanks in Advance
Shree Nivas Kushwah

**Comment by mairaw** [comment]
Were you running the Blazor tutorial when you encountered this issue?
https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run 

Did you make any changes to template code before running into this?

Adding @danroth27 for assistance.

**Comment by mairaw** [comment]
Can you try creating the project with no spaces in the name? I'd like to confirm a hypotheses we have.

**Comment by ErNivasIT** [comment]
Thanks lot,
It works.

Shreeniwas Kushwah

*Senior .Net Developer*

*MAPIT Bhopal*

**Comment by mairaw** [comment]
Glad to hear and thanks for letting us know. This is also a known bug that is being tracked to fixed.
Check https://github.com/dotnet/aspnetcore/issues/52519 for more information.
