### ISSUE TITLE
error NU1301: The local source 'C:\Users\<username>\ source\repos\FirstClassLibrary\bin\Debug' doesn't exist.

### ISSUE THREAD

**Issue by navedrasul** [dotnet/website-feedback#80]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/microservice-tutorial/create
Operating System: windows

Very first command on the tutorial page generates a dependency issue. Please add the missing step to add the missing library/project/package/etc.

**Comment by navedrasul** [comment]
here is the exact message when i run the command "`dotnet new webapi -o MyMicroservice --no-https`":

```
Determining projects to restore...
C:\Users\naved\code\repos\micros\MyMicroservice\MyMicroservice.csproj : error NU1301: The local source 'C:\Users\naved\
source\repos\FirstClassLibrary\bin\Debug' doesn't exist.
C:\Users\naved\code\repos\micros\MyMicroservice\MyMicroservice.csproj : error NU1301: The local source 'C:\Users\naved\
source\repos\FirstClassLibrary\bin\Debug' doesn't exist.
```

**Comment by mairaw** [comment]
Can you confirm this is the message you get when you're trying to create the project and not later on the tutorial? I usually see customers with this problem when they're in the Docker section.
