### ISSUE TITLE
Problemi terminale e debug dell'esempio tutorial

### ISSUE THREAD

**Issue by Xaltotun84** [dotnet/website-feedback#82]
Salve, faccio subito una premessa, usare visual studio code è difficilissimo, per fare qualsiasi cosa sono più le volte che non riesco a compilare o avviare il debug che altro. Detto questo ho seguito il vostro tutorial per la scritta hello world, al punto dell'esecuzione nel programma avvio il run associato al file mi genera questo errore: Impossibile trovare il progetto che contiene 'e:\Documenti\Progetti C#\Workspace\ConsoleApp1\Program.cs'

Se invece eseguo lo stesso comando ma sul file ConsoleApp1.csproj invece che sul terminale ma sull'output vedo l'esecuzione come dal vostro esempio.

Altri problemi riscontrati che non trovo tutorial a riguardo è la possibilit1a di scrivere il codice in C ma poi convertirlo in codice assembly, se fosse possibile fare un tutorial a riguardo mi sarebbe molto utile.

Sto seguendo anche un tutorial di un utente di youtube ma mentre a lui fa il debug a me viene generato questo tipo di errore:

[Running] scriptcs "e:\Documenti\Progetti C#\Workspace\Avventura_testuale\Main.cs"
"scriptcs" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

[Done] exited with code=1 in 0.03 seconds

Non riesco a capire cosa vuole

**Comment by Xaltotun84** [comment]
Il tutorial che seguivo dell'utente YouTube è questo... https://youtu.be/vAo2aTfp3cg?si=RzZVMJhmPscNWgO2 mentre invece seguivo un utente che scriveva il codice in C e poi lo compilava in assembly ma lui non mi ha spiegato come si fa e su YouTube non ho trovato niente a riguardo se vuole seguirlo a questo link https://youtu.be/nz4ONbac_sk?si=UcpkneHrvF8OLJd_ al minuto 20/21 circa

**Comment by mairaw** [comment]
On this tutorial, you could try getting a basic project to run in VS Code?
https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/intro

Once you get the project running, you could follow the first tutorial to try to make that code work.

We'll be launching the site soon in Italian too.

**Comment by Xaltotun84** [comment]
ok grazie, comunque sono riuscito a capire che questo errore:
[Running] scriptcs "e:\Documenti\Progetti C#\Workspace\Avventura_testuale\Main.cs"
"scriptcs" non � riconosciuto come comando interno o esterno,
un programma eseguibile o un file batch.

[Fatto] è uscito con codice=1 in 0,03 secondi

è generato quando il compilatore non porta a termine la compilazione ma non ho ancora capito come risolvere l'avviso che mi viene fuori dove nel progetto ho la riga Console.ReadLine(); nella pagina del terminale io voglio che abbia un valore null perchè sono io a scegliere che cosa scrivere ma solo da terminale non che debba dargli per forza un valore dal programma. E quindi lui me lo vede come un problema, come anche una variabile string che si prende un valore quando io la scrivo sul terminale non prima e lui la vede come un problema.

È un mio pensiero personale ma secondo me i tutorial ti fanno vedere un progetto che funziona quindi vengono fatti da persone che sanno fare, secondo me prima va presentato il progetto di uno che sta imparando a programmare e quindi genera un sacco di errori poi si fa vedere come si correggono e si spiega dove sta l'errore, oppure come andare a sostituire una parte perchè la libreria ha subito un miglioramento e un cambiamento. Ma tra quelli che postano i vari progetti che rimangono a metà e le librerie che cambiano per migliorare e correggere eventuali errori, (tipo dal .net8 è stato tolto il BinaryFormatter che nel progetto che stavo seguendo è presente e non ho ancora capito come sostituirlo con il streamreader e streamwriter) forse diventa impossibile?

Quando ho del tempo libero continuo a sbatterci la testa perchè tutorial di quello che voglio fare io ne ho trovati pochi e incompleti, però secondo me con i punti descritti sopra ci sarebbe un bel miglioramento. Poi vediamo quando il sito sarà in italiano se trovo altri aiuti :+1:  

Grazie per avermi ascoltato :)

**Comment by mairaw** [comment]
No worries! I wish I could reply in Italian. 

Yes, those are difficult problems to solve. Our goal with the simple tutorials is just to get you going and then you can start exploring more in-depth training at https://learn.microsoft.com/it-it/training/

For generating exe file, I think this article should help:
https://learn.microsoft.com/it-it/dotnet/core/deploying/#produce-an-executable
