### ISSUE TITLE
Downloading Arm64

### ISSUE THREAD

**Issue by hhanse02** [dotnet/website-feedback#83]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

macos

### More information about your system

Arm64

### Description

I downloaded Arm64 however the code is not processing on my visual studio code terminal.

**Comment by mairaw** [comment]
Is your machine arm64? Do you have a Mac M1/M2?

What does `dotnet --info` return on your terminal?
