### ISSUE TITLE
.NET recommendation is not seeing

### ISSUE THREAD

**Issue by Sahillather002** [dotnet/website-feedback#84]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### Description

Couldn't able to see the .NET extension in search with Control + Shift + P

![image](https://github.com/dotnet/website-feedback/assets/72077931/3fb1f7a5-34ad-4b08-8fb8-2e54610455b2)

**Comment by mairaw** [comment]
Can you confirm the extension is installed?

![image](https://github.com/dotnet/website-feedback/assets/12971179/e5322791-865a-4f47-be97-6b47c9a9ce04)
