### ISSUE TITLE
Blazor web app template

### ISSUE THREAD

**Issue by glengoda** [dotnet/website-feedback#85]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### Description

hi, I dont have a Blazor web app template on my visual studio  and How can i add on my visual studio 2022

### dotnet --info

![image](https://github.com/dotnet/website-feedback/assets/124570581/9ccaf660-9e6c-41fe-83ad-72e49e4711d6)
![Screenshot 2024-03-04 134254](https://github.com/dotnet/website-feedback/assets/124570581/e3ab6aa5-170e-476a-bb01-269585ccc615)

**Comment by mairaw** [comment]
@glengoda can you confirm which version of Visual Studio you're running? 

It should be VS 17.8 or higher. 

You can to Help > About.

![image](https://github.com/dotnet/website-feedback/assets/12971179/b743c1fe-ece1-4cd9-9404-deffa9734fdc)

**Comment by glengoda** [comment]
It works!

**Comment by mairaw** [comment]
Great to hear.
