### ISSUE TITLE
 Support Hawaiian dialect on documentation site 

### ISSUE THREAD

**Issue by RobKenis** [dotnet/website-feedback#88]
### URL

https://dotnet.microsoft.com/en-us/apps/maui

### Current translation

Not supported

### Suggested translation

Hawaiian

### Additional context

Support Hawaiian dialect on https://dotnet.microsoft.com/en-us/apps/maui. Their wikipedia page is above the framework documentation, so it's only fair.

**Comment by mairaw** [comment]
We only support the same languages that Visual Studio supports, so I'm closing this ticket.

But I'm curious on what kind of search you were doing? Not sure if I understand the request completely.
