### ISSUE TITLE
Opening Terminal / Output

### ISSUE THREAD

**Issue by Danielgeneralov** [dotnet/website-feedback#89]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/edit

### Operating system

macos

### Description

When I try to run the C# in VS code I can't find how to see the output. What is going on?

**Comment by mairaw** [comment]
The output should be in the terminal window like in the following image. Do you  get the same result?

![image](https://github.com/dotnet/website-feedback/assets/12971179/51704526-ec14-452b-a127-0be7d3846bc6)

/cc @claudiaregio @webreidi
