### ISSUE TITLE
https certificate failure

### ISSUE THREAD

**Issue by ew-1987** [dotnet/website-feedback#91]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create

### Operating system

windows

### More information about your system

x64 System IntelCore i7 6700k

### Description

When i start to debugg for https, i run in this error:
![image](https://github.com/dotnet/website-feedback/assets/150849309/d9d1bfe5-dcbf-43c7-ada2-db9fb1e31a68)
If i change it to http, it will work fine.

### dotnet --info

![image](https://github.com/dotnet/website-feedback/assets/150849309/11f1f907-09b6-4a04-ab10-37e2742a2aee)

**Comment by ew-1987** [comment]
I have not seen that at the end of the page, there was the solution. I had to close the webbrowser.

**Comment by mairaw** [comment]
Yes, that's the workaround for now.
