### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by AnaFrasom** [dotnet/website-feedback#94]
### URL

https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### More information about your system

Windows 11, arquitetura x64

### Description

Eu clico em criar novo projeto e aparece essa mensagem na tela

![image](https://github.com/dotnet/website-feedback/assets/117923892/3283eeae-765c-4941-8444-7ad12d1a3eaa)

**Comment by mairaw** [comment]
@AnaFrasom e você instalou o .NET SDK no passo anterior? Se sim, ja tentou reiniciar o VS Code? Se sim, você pode digitar o seguinte comando no terminal do VS Code e dizer o que retorna?
`dotnet --info`

**Comment by AnaFrasom** [comment]
Olá, aparece isso aqui

Host:
  Version:      8.0.2
  Architecture: x86
  Commit:       1381d5ebd2
  RID:          win-x86

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS C:\Users\anacl\OneDrive\C#>
________________________________
De: Maira Wenzel ***@***.***>
Enviado: segunda-feira, 11 de março de 2024 23:28
Para: dotnet/website-feedback ***@***.***>
Cc: Ana Clara ***@***.***>; Mention ***@***.***>
Assunto: Re: [dotnet/website-feedback] Erro (Issue #94)


@AnaFrasom<https://github.com/AnaFrasom> e você instalou o .NET SDK no passo anterior? Se sim, ja tentou reiniciar o VS Code? Se sim, você pode digitar o seguinte comando no terminal do VS Code e dizer o que retorna?
dotnet --info

**Comment by mairaw** [comment]
Como vc já confirmou que seu computador é x64, deve ser um problema com o PATH.

Rode o comando `where.exe dotnet` para ver se o x86 aparece primeiro. Se sim, siga os passos para arrumar o seu PATH como explicado nesse meu comentário:
https://github.com/dotnet/core/issues/5962#issuecomment-780084535
