### ISSUE TITLE
Solution Explorer folder is not show in VS Code app

### ISSUE THREAD

**Issue by NipunaMalinga** [dotnet/website-feedback#95]
### URL

https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create

### Operating system

windows

### Description

When I tried to start making a new console app in VS code application in C# there is not folder called solution explorer at the left side pane in the application.
![VS code](https://github.com/dotnet/website-feedback/assets/39951431/cb7ed5cf-bb5f-44c7-9529-3a8cec12308e)

**Comment by mairaw** [comment]
Did you install the C# Dev Kit extension?
