### ISSUE TITLE
Install dotnet in terminal

### ISSUE THREAD

**Issue by gameplaybiel** [dotnet/website-feedback#96]
### URL

https://dotnet.microsoft.com/pt-br/learn/dotnet/hello-world-tutorial/install

`PS C:\Users\018444631\Documents\C#> dotnet
dotnet: The term 'dotnet' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

### Operating system

windows

### More information about your system

x64

### Description

Dotnet in terminal PowerShell

**Comment by mairaw** [comment]
E você instalou o SDK? Abriu um novo terminal antes de digitar o comando `dotnet`?
