### ISSUE TITLE
Engineering electrical assessment career but sustainability 

### ISSUE THREAD

**Issue by t5h2i0tadi** [dotnet/website-feedback#97]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

linux

### More information about your system

Engineering 

### Description

electrical assessment career but sustainability 

### dotnet --info

Engineering electrical assessment career but sustainability

**Comment by t5h2i0tadi** [comment]
Engineering electrical assessment career but sustainability

**Comment by t5h2i0tadi** [comment]
Engineering electrical assessment career but sustainability

**Comment by mairaw** [comment]
Seems unrelated to the topic at hand. Closing.

**Comment by t5h2i0tadi** [comment]
Hello good like
