### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by Churchill-G** [dotnet/website-feedback#98]
### URL

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### More information about your system

.net 8

### Description

Blazor Tutorial:  When I run the app I get an SSL certificate warning.  If I accept the certificate the website shows a warning that this is unsafe.

**Comment by mairaw** [comment]
Is the certificate warning like the one is shown on that page?

![image](https://github.com/dotnet/website-feedback/assets/12971179/57c646fc-f0b3-444c-b618-4af43444ffb3)

Have you done those steps?

**Comment by nicasi** [comment]
Thanks, this solved the issue for me.

I skipped the "Got an error?" paragraph because it looked like a generic "got an error, report it at github" paragraph. Maybe the title could be more specific?

**Comment by mairaw** [comment]
@nicasi that's a good suggestion. I can try changing that and see if that would help others.
