### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by gavrifalcao** [dotnet/website-feedback#99]
### URL

https://dotnet.microsoft.com/pt-br/learn/aspnet/blazor-tutorial/run

### Operating system

windows

### More information about your system

Windows 11 Home Single Language, v. 22H2
.NET version: 8.0.3 (LTS according to the download page)
IDE: Microsoft Visual Studio Community 2022 (64 bits), version 17.6.4

### Description

Compilation started...
1>------ Compilação iniciada: Projeto: MyFirstBlazor, Configuração: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(151,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0. Target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0.
1>Build project "MyFirstBlazor.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 9:06 PM and took 00.145 seconds ==========

Everytime I try to run the project, I get this error.

### dotnet --info

.NET SDK:
 Version:           8.0.203
 Commit:            5e1ceea679
 Workload version:  8.0.200-manifests.4e94be9c

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.203\

Cargas de trabalho do .NET instaladas:
 [android]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    34.0.43/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.43\WorkloadManifest.json
   Tipo de Instalação:        FileBased

 [maui-windows]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    8.0.3/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo de Instalação:        FileBased

 [maui-maccatalyst]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    8.0.3/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo de Instalação:        FileBased

 [maccatalyst]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    17.0.8478/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.0.8478\WorkloadManifest.json
   Tipo de Instalação:        FileBased

 [maui-ios]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    8.0.3/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo de Instalação:        FileBased

 [ios]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    17.0.8478/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.0.8478\WorkloadManifest.json
   Tipo de Instalação:        FileBased

 [maui-android]
   Origem da Instalação: VS 17.6.33815.320
   Versão do Manifesto:    8.0.3/8.0.100
   Caminho do Manifesto:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Tipo de Instalação:        FileBased

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  7.0.304 [C:\Program Files\dotnet\sdk]
  8.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by mairaw** [comment]
Oi @gavrifalcao. Parece que o compilador não está enxergando essa versão que você tem instalado. Você pode me dizer o que o comando `where.exe dotnet` retorna pra você? Como ele encontrou outras arquiteturas instaladas (x86), queria ver se não é um problema de PATH na sua máquina.
